### ISSUE TITLE
IDEA: Separate the GUI from the project?

### ISSUE THREAD

**Issue by Dlol** [timothyschoen/PlugData#1]
I’m not too experienced in JUCE (or modern c++) but would it be possible to split the UI from this and make a standalone ver? It just looks really nice and I would like to use it standalone.

**Comment by timothyschoen** [comment]
PlugData can be used as either a standalone or a plugin. When building, choose the "standalone" target and you should be good to go!

Keep in mind that PlugData is not a finished product yet, I've currently only tested it on Mac (but it should work on Windows and Linux). It also needs to be tested more thoroughly, there might still be some bugs.

If you want seperate the GUI for another project without any puredata backend, I'd recommend deleting the "Source/Pd" folder and then start removing mentions of these objects from the code. I'm not sure if this is what you meant, but if it is, it'll be quite a lot of work.

Does this answer your question?

**Comment by Dlol** [comment]
Yes it does! I could help with testing a bit since winter break is starting soon and I’m on linux.
