### ISSUE TITLE
Subpatches and Abstractions don't hide when in Presentation mode

### ISSUE THREAD

**Issue by alfonso73** [timothyschoen/PlugData#102]
Subpatches and Abstractions don't hide when in Presentation mode

<img width="407" alt="subpatches and abstractions in presentation mode" src="https://user-images.githubusercontent.com/3230434/168072748-f1095054-f1b6-4e27-a739-96934131335a.png">

**Comment by timothyschoen** [comment]
Thanks, I'll fix that!

**Comment by timothyschoen** [comment]
Fixed!
