### ISSUE TITLE
win10 vst - arrays acting funnky/buggy

### ISSUE THREAD

**Issue by offthesky** [timothyschoen/PlugData#103]
im working on a knob recorder patch(attached), the first array "knob_value" seems to retain the recording on reload but the 2nd array, knob_value2 doesn't. is this a bug? or perhaps im just screwing something up there.  

also, should there be properties when you click on the array gui object - such as ability to change the name/size of an array after you create it?  

also if i open up the same patch twice (two tabs in plugdata), i get a ton of "warning: "XX array name" multiply defined"  errors, and then the daw crashes
[knob recorder x2.zip](https://github.com/timothyschoen/PlugData/files/8683874/knob.recorder.x2.zip)

**Comment by timothyschoen** [comment]
Nice patch idea! The same happens when you open the patch twice in pd-vanilla:

<img width="612" alt="Screenshot 2022-05-13 at 13 42 24" src="https://user-images.githubusercontent.com/44585538/168276261-380a2fe2-03e5-4057-bf1c-d0be1cd7b26f.png">

The crash is probably because PlugData's console gets overloaded with messages, that should be fixed. I think the console in PlugData is still much too slow...

**Comment by timothyschoen** [comment]
I'll make sure to add list properties soon, it's kinda important if people are learning pd with PlugData that all features are actually in there. Another thing that's missing is some canvas properties and the ability to set canvas options on the current canvas.

**Comment by offthesky** [comment]
ah having those properties available to edit in plugdata would be amazing. now that i've messed with pd-v for a little while this morning, am actually quite wishing it was as smooth/nice of a gui/ux experience as plugdata is ;]

**Comment by offthesky** [comment]
just trying out the arrays in the new .5.3. loving being able to edit the parameters of it in the right panel. sadly, once the array is made, the parameters won't save and im getting crashes on reload (but for some reason the 2nd time reloading the project then loads?).  this is a reaper project with only one instance of the .5.3 plugdata vst3i x64 with only one array inside, nothing else.  im also noticing the same behavior with older projects that use arrays in plugdata: crashes on load (but will load on the 2nd try) and any array's params i change, won't recall after the project loads, after that first crash.

**Comment by timothyschoen** [comment]
I found multiple problems looking into this, apparently Pd changed the interface for arrays at some point, which I didn't notice, so there was a problem that could potentially lead to crashes, and could also lead to losing your parameters.

There were also some parameters that weren't being initialised correctly. Both fixed now!
