### ISSUE TITLE
crash while typing the name of a newly to be created object

### ISSUE THREAD

**Issue by sevdh** [timothyschoen/PlugData#104]
Here follow 4 crash reports that happend while simply typing the name of a newly to be created object on macOS ARM

[plugdata crashes.zip](https://github.com/timothyschoen/PlugData/files/8695309/plugdata.crashes.zip)

**Comment by timothyschoen** [comment]
Thanks, they all seem to be caused by the same issue, are you using the last release or building from source?

**Comment by sevdh** [comment]
the last release: 0.5.2

**Comment by timothyschoen** [comment]
Is this caused by pinch-zooming with the editor open?

**Comment by sevdh** [comment]
I'm not doing any (intentional) pinch-zooming but will try your suggested version

**Comment by sevdh** [comment]
It still happens with the new version:

[PlugData-2022-05-15-175342.ips.zip](https://github.com/timothyschoen/PlugData/files/8695333/PlugData-2022-05-15-175342.ips.zip)
:

**Comment by timothyschoen** [comment]
Thanks for testing it out, I'll look into it!

**Comment by timothyschoen** [comment]
Fixed it! Thanks for reporting!
