### ISSUE TITLE
Keyboard shortcut for opening help patch

### ISSUE THREAD

**Issue by sevdh** [timothyschoen/PlugData#106]
I would expect to be able to open the help patch of an object by option-clicking on it (or another key combination).

I can't figure out how to do it and maybe it is (intentionally) not implemented.

**Comment by timothyschoen** [comment]
Not intentional, currently it's only possible by right-clicking. I'll add a keyboard shortcut soon!

**Comment by sevdh** [comment]
Then it should simply be control-click on macOS

**Comment by timothyschoen** [comment]
I don't think pd has this shortcut (or at least it didn't work for me) but I found in Max the shortcut is option/alt + click, so I implemented it like that.

**Comment by sevdh** [comment]
That's correct. Really nice that this is implemented and it's possible to directly open the help patch.

CTRL + click is normally identical to a right click which is currently not implemented in PlugData but probably not really necessary either.
