### ISSUE TITLE
When you move an object you either get horizontal alignment or vertical alignment (to other objects) but not both

### ISSUE THREAD

**Issue by sevdh** [timothyschoen/PlugData#108]
While moving/positioning an object it would be fantastic if it can snap (to other objects) simultaneously in both the horizontal direction and the vertical direction. Currently only one of the two works at a time which is great but the simultaneous behaviour would be a very nice addition and very helpful to position objects.

**Comment by timothyschoen** [comment]
Agreed, I'll definitely add this!

**Comment by timothyschoen** [comment]
![Screen Recording 2022-05-17 at 19 04 50](https://user-images.githubusercontent.com/44585538/168870885-a0c86a65-c044-4ca4-b185-59fbe4b2baef.gif)

Done!

**Comment by sevdh** [comment]
Wat goed!

On 17 May 2022, at 19:07, Timothy Schoen ***@***.***> wrote:

﻿


Done!
