### ISSUE TITLE
Have to use LC_ALL=C for floats to work correctly

### ISSUE THREAD

**Issue by zkf** [timothyschoen/PlugData#109]
Looks like handling of floats may be locale-dependent. Unless the env var `LC_ALL=C` is set, a `[float]` such as `0.5` may be displayed as `0,5` or just `0`. This happens after saving a patch and reloading Plugdata. Happens in Ardour on Linux.

Differences between VST3 and LV2:

- LV2 saves the float value `0.5` as `0` (truncated) in the patch file.

- VST3 saves the float as `0,5`. When reloading the file, the error `canvas: no method for float` is logged.

**Comment by timothyschoen** [comment]
I've added ```std::setlocale(LC_ALL, "C");``` to the constructor of the plugin processor, I'll test if that works in a minute. I'm also not sure how else I could set an environment variable in a plugin.

It's interesting though, because a plugin usually runs on the same process as the host. Does it share locale settings with the host?

**Comment by timothyschoen** [comment]
I'm struggling to reproduce this issue on Linux, I've set my locale to nl_NL.UTF-8 which should use commas instead of periods for decimal numbers, but if I save a patch with [float 0.5] either as DAW preset or pd patch, it works fine.

**Comment by zkf** [comment]
Sorry, I should have been clearer on how to reproduce. Here are exact repro steps on Linux (tested with nl_NL.UTF-8 locale. Hope this helps!):

```
LC_ALL=nl_NL.UTF-8 ardour6
new session
empty template
add new empty midi track
add plugdatafx instrument plugin lv2
new object, [f 0.5]
save project -> save file
close plugin window
save session
close ardour

LC_ALL=nl_NL.UTF-8 ardour6
open previous session
open plugin window (note: no patch seems to be loaded)
open project -> select previously saved file
observe object [f 0]
hit save
object is now saved as f 0 in patch file
update object to [f 0.5] again
hit save
object is still f 0 in patch file.

bonus:
add new object [f 0.75]
hit save
in the patch file, the new object is saved as f 0,75 (with comma)
```

**Comment by timothyschoen** [comment]
Thanks, that'll help me reproduce!

**Comment by timothyschoen** [comment]
I can reproduce and it seems the std::setlocale solution works!
