### ISSUE TITLE
Mac 11.6.4 / Logic Pro X 10.7.4 crashes in use

### ISSUE THREAD

**Issue by donnerbono** [timothyschoen/PlugData#111]
E.g closing a sub patch window. Think adding number box did the same. Crashed 3 times in about 10 minutes so can't use yet.

Great project!

**Comment by timothyschoen** [comment]
Thanks for reporting! Are you using the latest release version or are you building from source? There are some bugs in the last release that are solved by downloading the latest build here:

https://github.com/timothyschoen/PlugData/actions/runs/2346935263

**Comment by donnerbono** [comment]
<img width="251" alt="Screenshot 2022-05-18 at 19 27 13" src="https://user-images.githubusercontent.com/25040742/169118392-cf2859c3-ae87-4334-bb10-3c1b9cd6d92c.png">

I get that when replacing with those components for all 3.

**Comment by timothyschoen** [comment]
Sorry, I forgot about Apple's notarisation requirement. I wanted to notarise this version for you real quick, but unfortunately I can't upload files that big over here.

**Comment by donnerbono** [comment]
No rush. Let me know when it's done and I'll have a play again. Plenty of other things to play with in the meantime!

**Comment by timothyschoen** [comment]
I've just uploaded a new version, I'm curious to see if you still experience those problems

**Comment by timothyschoen** [comment]
This is probably fixed, but feel free to reopen if it's not
