### ISSUE TITLE
GraphOnParent in abstraction isn’t displayed in parent patch

### ISSUE THREAD

**Issue by zkf** [timothyschoen/PlugData#113]
A GraphOnParent created in an abstraction isn’t drawn in the patch using the abstraction. I can, however, create a patch doing this in vanilla PD and open it in PlugData. So I think it’s just the creation that is in error.

**Comment by zkf** [comment]
Sorry for not being clear. Here’s an example, open testabs.pd in PlugData!

[PlugData.zip](https://github.com/timothyschoen/PlugData/files/8719344/PlugData.zip)

**Comment by timothyschoen** [comment]
No problem, I'm already happy you're taking the time to report the issues you find!


<img width="518" alt="Screenshot 2022-05-18 at 20 47 24" src="https://user-images.githubusercontent.com/44585538/169123661-9569be73-703c-42e9-88ad-8c96e7a1430e.png">

I see a few things wrong here:

1. No title
2. Atom boxes are showing even though they shouldn't (sometimes also an issue with other objects)

**Comment by zkf** [comment]
3. Also I wasn’t able to create this in PlugData, I had to use vanilla :)

**Comment by timothyschoen** [comment]
Ah, I get it now!

**Comment by zkf** [comment]
Ah I see now. But in order for that to work correctly you have to delete the original GraphOnParent that you created in the main patch, and create a new object with the name of the file you just saved (minus the .pd extension). Otherwise there won’t be a link to the new abstraction in the patch. It looks like it just writes the contents of the graph into the main file instead of linking to it.

**Comment by timothyschoen** [comment]
You can now do this!

https://user-images.githubusercontent.com/44585538/170610491-f62f8703-532d-4237-a0c4-3fd60196e9a0.mov

**Comment by timothyschoen** [comment]
You can also convert between subpatches and graphs without opening them now
