### ISSUE TITLE
Add libcurl-openssl as a dependency on AUR

### ISSUE THREAD

**Issue by timothyschoen** [timothyschoen/PlugData#114]
@aik2mlj Could you add this dependency? This is now a requirement for the built-in Deken support.

**Comment by aik2mlj** [comment]
Hi the package name seems different on arch. I guess it's simply the `curl` package?

**Comment by timothyschoen** [comment]
I think that should be fine, it's really a technicality because almost everyone has this package installed.

**Comment by aik2mlj** [comment]
Sure! Added now. Love your work!

**Comment by timothyschoen** [comment]
Thanks!!
