### ISSUE TITLE
Linux packages

### ISSUE THREAD

**Issue by KottV** [timothyschoen/PlugData#115]
Hi!

I saw you've added various Linux distro in the GH Actions.
Would You interested to use OBS (Open Build Server) for that task? If yes - I can help with most steps.
It has some advantages, main - the published repository which can be added to package manager. Rebuilds can be triggered from GH https://openbuildservice.org/2022/04/04/scm-integration-trigger_services/ (yes, a bit tricky)

I've one for the BespokSynth https://build.opensuse.org/package/show/home:bespokesynth/bespokesynth-current
also PlugData just for openSUSE https://build.opensuse.org/package/show/multimedia:proaudio/PlugData

**Comment by timothyschoen** [comment]
I'd love that, but unfortunately I have no experience with this kind of stuff, as is evidenced by the amount of time it cost me the get these actions running. Cool that you made it available on OpenSUSE already! If you could guide me through the process, I'd appreciate it. Somewhere next week I'll have some time to look at it.

**Comment by KottV** [comment]
Good, I'll make the repository (home:plugdata) and the all other stuff, so, you don't have to worry about, and have more time on development:)

**Comment by KottV** [comment]
I made a packages https://software.opensuse.org//download.html?project=home%3Abespokesynth&package=plugdata
it's a temporary repository (bespokesynth), once `home:plugdata` be available I'll move it there
here is the package repo: https://build.opensuse.org/package/show/home:bespokesynth/plugdata
we have openSUSE/Fedora and Debian/Ubuntu/Raspbian with arm7 and aarch64 architectures

I can make the new repo (home:plugdata) by my own, but it will be registered with my e-mail.

**Comment by timothyschoen** [comment]
Wow that's very impressive, thanks for doing this! Does it need to be updated manually, or will it auto-update on push or release?

**Comment by KottV** [comment]
>Does it need to be updated manually, or will it auto-update on push or release?
For now, it has to be triggered manually (just one command or click). I'm working on the GH integration, it shouldn't be hard.

> I do wonder, why no Arch version? It's not a big deal since it's already on the AUR, but it might be nice.
I excluded Arch for exact reason - PlugData is in AUR, no problem, I'll add in next day.

**Comment by timothyschoen** [comment]
If there's anything I need to do to make GitHub integration work, let me know! IIRC I can set up a URL hook whenever I push something, this is commonly used for updating websites from git source.

I think adding Arch is fine because the AUR will build from source. This is undesirable is your PC is very slow.

**Comment by KottV** [comment]
Good, thanks! Ok, I'll make a new repo for the PlugData only, then send you a token. Give me a day or so, please.

**Comment by timothyschoen** [comment]
Take your time, no need to hurry!

**Comment by KottV** [comment]
Indeed, adding a hook was a simple task. But I screwed the creation of new "home" by passing wrong e-mail, need to wait until the logon service cancel it :)

**Comment by KottV** [comment]
There we go https://build.opensuse.org/package/show/home:plugdata/plugdata
The e-mail was sent :)

**Comment by timothyschoen** [comment]
Nice, thanks for setting it up! I've pushed something so it should be recompiling now. I also saw the armv7 and armv6 versions failed compilation because of a typo, that should be fixed as well!

I'll add a link in the readme, and I'll be advising Linux users to install it from here as well, since it means they have a much simpler installation process and also get instant updates if they use the repo!

**Comment by timothyschoen** [comment]
Okay so apparently, you also need to enter a GitHub token into OBS to give it access to GitHub. Did you use your own personal access token for this? Because then it might work if I give you admin rights, or I could mail you an access token for PlugData if you prefer that?

**Comment by KottV** [comment]
I sent you an OBS token at June 1 with instructions, it should at GH page of PlugData, have you received it?

>I've bumped the version number to 0.5.3
`git describe --tags` shows `v0.5.2-205-g10f68400`

**Comment by KottV** [comment]
bundled fluidsynth gives a troubles here

**Comment by timothyschoen** [comment]
Ah I understand how it finds the version tags now, thanks! I'm still not sure if the automatic hook works, on github it still says my hook returns an error.

There are a few new dependencies for fluidsynth, all of them are only needed for building, not for running. These are python, xz, wget, tar and gzip. Some distros are shipped with all of these, but some are not.

Worst case scenario, you can disable fluidsynth by passing `-DENABLE_SFONT=0`,  this will mean users won't have access to the sfont~ object. 

You're building for a few more architectures than I am, so you may run into problems, in that case you might want to disable sfont for those architectures. I'm optimistic it will work though! I've tested it on x64 and ARM64 Linux.

**Comment by KottV** [comment]
The main problem OBS hasn't internet access and can't download any, you have to provide all sources in the build tree.

**Comment by timothyschoen** [comment]
That's rough. I guess I'll just add all the folders to the project then.

**Comment by KottV** [comment]
I'll provide packages without soundfont support for now.
What we need here (as I can see) - is to build statically linked with fluidsynth. I'll try to find a nice way for that.

**Comment by timothyschoen** [comment]
I'm just going to add the dependencies to the project, it's only 15mb so it's fine. It makes the build more reliable if we don't rely on a network connection anyway!

If [these tests](https://github.com/timothyschoen/PlugData/actions/runs/2719817690) pass, you should be good to go!

**Comment by timothyschoen** [comment]
I guess I'll close this because there aren't any issues, but feel free to drop any Linux Package related issues here.
