### ISSUE TITLE
juceaide build fails on Arch

### ISSUE THREAD

**Issue by aik2mlj** [timothyschoen/PlugData#116]
Hi I encounter this error recently.
```
PlugData/Libraries/JUCE/modules/juce_gui_basics/windows/juce_ComponentPeer.h:504:18:
error: ‘exchange’ is not a member of ‘std’

504 |         if (std::exchange (style, s) != style)
	|                  ^~~~~~~~
```

Guess it's due to unmatched C++ version?

**Comment by timothyschoen** [comment]
I got this error too when creating the GitHub build action, the solution is to use gcc-11 instead of gcc-12, like this:

```
pacman -S gcc-11

CC=/usr/bin/gcc-11 CXX=/usr/bin/g++-11 cmake ..  -G "Unix Makefiles" 
```


Strange though.

**Comment by timothyschoen** [comment]
We should probably report this to the JUCE team

**Comment by timothyschoen** [comment]
They already fixed it, but the repo isn't updated yet
