### ISSUE TITLE
The program window almost completely transparent after introduction of theming feature

### ISSUE THREAD

**Issue by zkf** [timothyschoen/PlugData#118]
Commit 83fa22f introduced a bug which makes the program window almost wholly transparent (standalone mode, Arch Linux).

![image](https://user-images.githubusercontent.com/613216/169657158-e49cb5ff-304d-4f64-bb7c-b4353c76fe2b.png)

**Comment by timothyschoen** [comment]
I noticed, if you remove ~/.config/PlugData/settings.xml, it's fixed

**Comment by zkf** [comment]
Thanks, that fixed it for me!

**Comment by timothyschoen** [comment]
It should happen anymore now!
