### ISSUE TITLE
UI elements missing linux 20 cinnamon 64 bit, tested in reaper and carla

### ISSUE THREAD

**Issue by TheGuyWhoo** [timothyschoen/PlugData#121]
Present in all variants. 

![Screenshot from 2022-05-21 17-34-42](https://user-images.githubusercontent.com/72744967/169658788-0da2ef0e-0cf1-4c9b-95f1-4ff35346482e.png)

**Comment by TheGuyWhoo** [comment]
I should also mention there's nothing new in the carla logs, just the juce assertion failure stuff and a mention it's using x11 lv2 ui, but on previous builds that was also present and ui still showed up fine.

**Comment by zkf** [comment]
I think this is the same as #118, it just presents differently when running in plugin mode.

**Comment by timothyschoen** [comment]
Removing ~/.config/PlugData/settings.xml will probably fix this, real solution coming soon!

The problem is the new theming feature: is sees there's a settings file, but it can find any colours so they end up transparent

**Comment by timothyschoen** [comment]
Already fixed, so you can also just pull the last version!
