### ISSUE TITLE
Label property with '$1' is overwritten with 0 when patch is loaded

### ISSUE THREAD

**Issue by zkf** [timothyschoen/PlugData#126]
[test-label-params.pd.txt](https://github.com/timothyschoen/PlugData/files/8749773/test-label-params.pd.txt)

![image](https://user-images.githubusercontent.com/613216/169705397-7c8dd376-70f4-4ff5-bee0-32adc65d3314.png)

**Comment by timothyschoen** [comment]
I'll check it out! I'm currently doing an enormous rewrite (on the develop branch), so it'll take me a bit of time to get to these bugs. The good news is that performance and maintainability are going to be much better!

**Comment by zkf** [comment]
Awesome!

**Comment by timothyschoen** [comment]
Fixed!
