### ISSUE TITLE
Printing a list prints each element in a new line

### ISSUE THREAD

**Issue by TjShredder** [timothyschoen/PlugData#134]
I come from Max, and thus need a lot of testing by printing results to find out whats going on. But if I print a list, its not printed as such like in Max/Pd, instead it puts out each element on a new line. I can't distinguish between a list and values which come one after another...
PlugData 0.5.3 preview...

**Comment by timothyschoen** [comment]
Thanks for reporting! I've heard about this before, it's unfortunately not easy to solve. I'll make sure it works before I release 0.5.3!

**Comment by timothyschoen** [comment]
I've copied the behaviour from Camomile, it should be fixed now!
