### ISSUE TITLE
Crashes when deleting/redefining/undoing an object MacOS

### ISSUE THREAD

**Issue by JoshuaACNewman** [timothyschoen/PlugData#136]
When I delete or redefine an object, it very often crashes the program. It doesn't seem to happen most of the time if there's not an error in it, but if there's a typo or other sort of mistake, it crashes immediately. It happens also if I undo a misplaced object.

...perhaps this is a permissions issue?

**Comment by timothyschoen** [comment]
Doesn't sound like a permissions problem, what version are you using? I've fixed many of these bugs recently, so if you get the latest version from the Actions tab, it might work better.

**Comment by JoshuaACNewman** [comment]
0.5.2.

Last night, I deleted /Library/PureData and I haven't been able to reproduce the bug. I'd already done that, but I wanted to make sure that I hadn't done something else in the interim.

**Comment by timothyschoen** [comment]
Thanks for reporting! I'll see if I can reproduce it

**Comment by timothyschoen** [comment]
I think this is fixed by 301eec33e35893681b0878c734f1532b1283ff71, I've been trying for a while and I haven't been able to get this crash anymore. Let me know if you find it happens still!

**Comment by timothyschoen** [comment]
I think this is fixed, but feel free to reopen if it isn't
