### ISSUE TITLE
Metro not passing bangs to noteout

### ISSUE THREAD

**Issue by vprknt** [timothyschoen/PlugData#139]
The below example seems to work in PureData (standalone) to continuously trigger MIDI notes. However the same does not work in PlugData. Manually clicking the bang object does produce a note, however.

![image](https://user-images.githubusercontent.com/9270936/175822335-b8225c5b-fc18-451f-bb26-b08770150932.png)

**Comment by timothyschoen** [comment]
Thanks for reporting! I've seen this bug before, I thought I fixed it. May have un-fixed it accidentally, I'll look into it!

**Comment by timothyschoen** [comment]
Are you using PlugData in a DAW or as a standalone? Are you using v0.5.2 or building from source?

**Comment by vprknt** [comment]
I'm using v0.5.2 in Reaper

**Comment by timothyschoen** [comment]
I've confirmed this issue with v0.5.2, it's fixed in v0.5.3. You'd have to build the latest version yourself. If you're not using Mac, you can also use the builds from the actions tab. I'm hoping to release v0.5.3 coming week!
