### ISSUE TITLE
UI feature request: hyperbolic panning

### ISSUE THREAD

**Issue by JoshuaACNewman** [timothyschoen/PlugData#141]
This is something I've dreamed of for a long time:

The closer an object is to the center of the screen, the larger and more detailed it is. The further from the center of the screen, the smaller and more abstract it is.

Up close, the features usually available in the righthand column are listed, checkboxes and all. If it's an abstraction, you can click to open the abstraction from here.

Far away, all you see is an abbreviation of the name and its I/O with connections.

All objects in the patch are visible at all times. You can always see the entire patch, so that large, complex patches are still visible with the parts you're working on now both traceable and easily understandable/manipulable. Holding down a key, Right-dragging, or scrolling with the scroll wheels moves the focus around. You can also move your POV by following specific edges, walking through the patch.

(A simpler, more obvious, more information-impoverished version of this is being able to pan around irrespective of where the patch is on the workspace. You don't have any peripheral vision this way, but it would still allow one to find the section to look at and put it in the center of the screen.)

**Comment by timothyschoen** [comment]
It would be a cool feature, however, it would mean I'd have to completely rewrite and redesign almost everything. From my previous experience, I've found that sticking to the way Max and Pd do things is often wise because that's what people are used to anyway.

I'm afraid I won't be doing this right now, but if anyone wants to fork it and implement it themselves, I'd love to see it.

**Comment by JoshuaACNewman** [comment]
I recognize this is a lot of work that's, at best, for the future.

I wanted to put this note here, though, to have the discussion about ways to represent this kind of information. Scrolling works in text because text is fundamentally one-dimensional, so every idea comes after it. Programming is a list of concatenated lists of characters. But 2D programming isn't. It matters where something is in both directions, and it squares the search space when looking for an idea.

There's an additional flaw in my proposal, which is that we don't actually care about distance in a PlugData workspace. Distance is really only a matter of what's legible. What matters is what's next on a wire (and what's after that). Which means that there may be another, more effective visualization, anyway.

**Comment by timothyschoen** [comment]
I definitely see the benefit of a system like this (also for touchscreen interfaces!), my concerns are more related to how hard this would be to implement, and how easy it is for systems like this to get in the user's way if you don't handle it perfectly. On top of that, there are many people who are already comfortable with the way Pd/Max works, so changing it will actually make it feel less familiar for a lot of people.

**Comment by JoshuaACNewman** [comment]
Yes, valid concerns.

Is there a place to discuss big picture ideas about PlugData? Proposing this out of the blue as a feature request is much worse that a running design discussion.

**Comment by timothyschoen** [comment]
The discussions page would be the place currently, but I feel like we could use a better place for it. If you post it in discussions, very few people who might be interested in participating in such a discussion will be notified. Maybe a discord server would be better?

**Comment by timothyschoen** [comment]
I've created a discord here:

https://discord.gg/eT2RxdF9Nq
