### ISSUE TITLE
Canvas gui shrinking issue

### ISSUE THREAD

**Issue by 60-hz** [timothyschoen/PlugData#145]
- create a canvas using "+"
- add a message or any gui box
- click on the message or gui box in edit mode -> the canvas will shrink one pixel width and height...

Also, canvas color is a bit too dark for a default color... it would be ideal with lighter gray, but it's not a big issue...

Plug data 0.5.3 standalone & MacOS 12.2.1

**Comment by timothyschoen** [comment]
Thanks, I can reproduce this. Weird bug too, should be fixed soon

**Comment by timothyschoen** [comment]
Fixed!

**Comment by timothyschoen** [comment]
Oh I'll adjust the colour as well
