### ISSUE TITLE
Characters break in comments

### ISSUE THREAD

**Issue by 60-hz** [timothyschoen/PlugData#146]
Some special character are breaking the comments:

Example with "->" that displays an arrow:

<img width="148" alt="Capture d’écran 2022-06-29 à 17 41 10" src="https://user-images.githubusercontent.com/5449719/176478766-0f728d4b-3f29-4fbd-8c99-221e4fccba13.png">

<img width="124" alt="Capture d’écran 2022-06-29 à 17 41 15" src="https://user-images.githubusercontent.com/5449719/176478770-c24a5a71-6e3f-4cc8-9cf5-7e260f6a1a4e.png">

Plug data 0.5.3 standalone & MacOS 12.2.1

**Comment by timothyschoen** [comment]
I'll look into this, probably related to juce::String encoding this differently than pd?

**Comment by timothyschoen** [comment]
Appears to be MacOS specific, weird problem for sure.

**Comment by timothyschoen** [comment]
This is a bug in JUCE, the only solution is to use a font that doesn't contain these symbols. I've removed all the arrows from the default font. If you use a custom font, you may still run into problems though.
