### ISSUE TITLE
Crashes when not defined object/function is entered into object (linux)

### ISSUE THREAD

**Issue by mantsar** [timothyschoen/PlugData#148]
Hello,

Standalone and plugin version just crashes when I enter something like "aaaa" or "noteiut" in object. Basically non existent function.  It happens on linux.

Terminal dumps:

```
 /usr/include/c++/12.1.0/bits/basic_string.h:1304: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::reference std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::back() [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; reference = char&]: Assertion '!empty()' failed.
zsh: IOT instruction (core dumped)  plugdata
```

**Comment by timothyschoen** [comment]
Thanks for reporting, I missed this problem because it somehow doesn't happen on Mac. I can reproduce it on Linux, fix coming soon!
