### ISSUE TITLE
Host Tempo/BPM

### ISSUE THREAD

**Issue by 8ouble-r** [timothyschoen/PlugData#15]
Is there a current (or planned) method of easily accessing the DAW/host tempo? As PlugData is obviously  plugin, the VST spec would allow it to access the host tempo.

**Comment by timothyschoen** [comment]
This is not implemented currently, but I think it's a great idea. I see this is implemented in Camomile so it should be easy.

**Comment by alfonso73** [comment]
Host tempo sync (with the deepest level of resolution (IIRC  samplePos) is an essential feature!

**Comment by timothyschoen** [comment]
![Screen Recording 2022-04-16 at 12 57 41](https://user-images.githubusercontent.com/44585538/163672482-ca111b7a-54c1-4d61-838f-749753c96a62.gif)

Works now! It uses the same format as Camomile, I figured that would be nice to ensure compatibility. I've added a playhead abstraction to make it a bit easier, but on the inside it just does this:

<img width="633" alt="Screenshot 2022-04-16 at 13 03 58" src="https://user-images.githubusercontent.com/44585538/163672576-ba41b89a-3d88-4e92-82ad-45bbea45f01c.png">

**Comment by alfonso73** [comment]
just great!!!!
