### ISSUE TITLE
Current master (4f9500a) fails on linking fluidsynth libs?

### ISSUE THREAD

**Issue by talaviram** [timothyschoen/PlugData#152]
Hi,
Feel free to close but as maybe the README.md isn't update.
I'm using Xcode 13.4.1 / macOS 12.4 (arm64).

I've pulled with submodules but still it seems there is `fluidsynth` missing for builds?

I get plenty of errors related to building fluidsynth.
```
clang: error: no such file or directory: '/Users/<user>/Developer/PlugData/build/Libraries/fluidsynth/lib/libfluidsynth.a'
```

**Comment by timothyschoen** [comment]
It should download and build fluidsynth when you configure the cmake project, but that requires you have the following dependencies installed: python, wget, xz, tar, gzip

You can also build without soundfont capabilities by adding `-DENABLE_SFONT=0` to your cmake command.

**Comment by talaviram** [comment]
Ahh. Thanks for the tip. (had everything except of `wget`).
Still on arm64 based mac I end up with:
```
src/ogg_opus.c:165:10: fatal error: 'opus/opus.h' file not found
#include <opus/opus.h>
         ^~~~~~~~~~~~~
1 error generated.
make[3]: *** [src/libsndfile_la-ogg_opus.lo] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all] Error 2
make: *** [fluidsynth_deps/Stamp/install-libs] Error 2
Error building fluidsynth: Libraries not found:
/Users/user/Developer/PlugData/build/Libraries/fluidsynth//lib/libfluidsynth.a
/Users/user/Developer/PlugData/build/Libraries/fluidsynth//lib/libsndfile.a
Disabling sfont object
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/user/Developer/PlugData/build
```

I suspect some header search path for opus is broken since I do have opus-1.3.1 with content under fluidsynth_deps.

I guess I need to follow the CMakeFiles to see where it goes wrong.

With:

```
-DENABLE_SFONT=0
```
It does build.
