### ISSUE TITLE
when copying/pasting arrays, then renaming the pasted array, the daw crashes

### ISSUE THREAD

**Issue by offthesky** [timothyschoen/PlugData#154]
tested in reaper x64 via Commit [a46b2be](https://github.com/timothyschoen/PlugData/commit/a46b2be40a6b8e39c42360bbe0678c9c81c1e8a1)

**Comment by timothyschoen** [comment]
I see, the problem is that I identified the arrays by name. Stupid mistake, it messes up when there are two identical arrays obviously. Fix coming soon, thanks for reporting!

**Comment by timothyschoen** [comment]
Array's are now handled by pointer instead of by name, which fixes it. It also fixes all those "duplicate array name" errors. Thanks again, this is a big improvement for arrays!

**Comment by timothyschoen** [comment]
There's still a problem with arrays inside subpatchers, I'll fix that tomorrow
