### ISSUE TITLE
vst3i buffer underruns/daw freezing when switched off for a while, then switched back on (also ableton crashes when replacing the vst3i instance)

### ISSUE THREAD

**Issue by offthesky** [timothyschoen/PlugData#155]
i've been swapping out all my patches from the v0.5.3 release plugin (7f6b939) into one of the latest vst3 builds and have been noticing that my patches that use the array object are causing very bad buffer glitches/daw freezes when i turn the devices on after a while.  the really odd thing here is that, the longer the plugdata instance (running the attached patch) are turned off/disabled, and then turned back on again, the longer the daw freezes.  but so far, the daw has always recovered (although sometimes it takes ages).  due to the generative nature of the installation im working on, my daw project needs these instances of plugdata to be able to be turned on/off at random times via midi, in order to save cpu. of course im not experiencing this problem at all with the array based patches using the v0.5.3 7f6b939 - last official release. im also not experiencing this problem with other patches in the latest builds. seems to only be these array based patches.

i've been able to repro this in both ableton 11 x64 and reaper x64/x32 on an 8 core macbook pro (running windows 10 pro latest update) and a 32bit windows10 tablet. first noticed the problem with the [e237b37](https://github.com/timothyschoen/PlugData/commit/e237b378ff41fe3773f4c6989468cf32e9226b51) build and then tried the latest build [24d25a0](https://github.com/timothyschoen/PlugData/commit/24d25a02cd11ab9d3d673f92dbdb0141815282b6) but of course the same problem is occurring there too.

attached is a reaper test project, and also an ableton als. also the .pd patched used in both.
[PlugData-CausingAudioDropouts.zip](https://github.com/timothyschoen/PlugData/files/9229614/PlugData-CausingAudioDropouts.zip)

again in order to experience this daw freeze problem, you music open the projects in the daw and let them run for a little while, then turn on(unmute, in the case of reaper) the plugdata instances.
 
also attached is a video demonstrating this problem.  let me know if there's anything else i can add or try here to help debug this!
https://user-images.githubusercontent.com/95579081/182043308-b6fa8d1f-ac81-4d8a-8ac0-a4542654aff7.mp4

one last bug: in ableton, when you drop another instrument on top of the plugdata vst3i, essentially replacing plugdata vst3i, ableton crashes. seems to occur even if the plugdata vst3i instance is empty (step 1 drop a plugdata vst3i instance into a track, step 2 drop operator or some other instrument on top of plugdata, ableton should crash)

.

**Comment by timothyschoen** [comment]
Thanks for reporting, I was having some problems because some DAWs stop the audio callback when there is no audio input, or when the track is not playing. I solved this by running a backup processing thread that takes over when the DAW stops playing, to make sure objects like [metro], [netreceive] and many more keep working if audio is paused. I suspect that this mechanism is causing problems.

I'll also look at the other bug. These reports are pretty useful, the release of 0.6.0 is coming up so any problems we can solve beforehand are a big win!

**Comment by offthesky** [comment]
awesome definitely happy to help try and make this thing as good as it can be :)

**Comment by timothyschoen** [comment]
Could you try the latest build? It should be fixed

**Comment by offthesky** [comment]
> Could you try the latest build? It should be fixed

bravo Commit [43150cf](https://github.com/timothyschoen/PlugData/commit/43150cfa6907d3b7a68c8b9d6dc2bfcfe3f1ae4f) seems to have done the trick!!

**Comment by timothyschoen** [comment]
Good! Unfortunately I fixed it by disabling the backup thread that takes over when the DAW is not playing audio, so now objects like [metro] won't do anything when there's no audio. I'll fix this later, because the current solution is still too buggy for the next release.
