### ISSUE TITLE
copying+pasting vst3i in reaper causes crashes

### ISSUE THREAD

**Issue by offthesky** [timothyschoen/PlugData#156]
steps to repro:
1. open up reaper, create and empty track
2. drag in the plugdata vst3i
3. load the attached "dc to midi note.pd" [dc to midi note.zip](https://github.com/timothyschoen/PlugData/files/9256712/dc.to.midi.note.zip)
)
4. using the keyboard, Ctrl+c to copy the plugin instance
5. Ctrl-V to paste a duplicate
6. Reaper should crash (see video).
occurs with Commit [43150cf](https://github.com/timothyschoen/PlugData/commit/43150cfa6907d3b7a68c8b9d6dc2bfcfe3f1ae4f) in windows 10 on 2 separate laptops (x64 and another x86)

https://user-images.githubusercontent.com/95579081/182766622-210310d0-6d06-4039-b699-804632d352c1.mp4

**Comment by timothyschoen** [comment]
I'm unfortunately not able to reproduce this in REAPER on Windows... I'll try it on my other Windows PC later. Did you get any kind of crash report?

https://user-images.githubusercontent.com/44585538/182842883-21bb1a22-ee2e-4efc-9d02-bcc1226571d6.mov

.

**Comment by offthesky** [comment]
for me i can get it to occur every time if i do the steps above right when reaper opens (not doing any other steps first). also i notice in your screen shot that you don't have separate tabs for the opened patch like im seeing, right after opening the dc to midi note.pd midi file:
![plugdata open patch puts it in separate tab](https://user-images.githubusercontent.com/95579081/182934798-e74f61da-5fa5-44ca-8e6a-2d3270225adc.png)
i can say if i close that empty(first) tab right after opening the .pd, and then copy paste the plugin, it doesn't seem to crash.

as far as crash report, have never actually looked for one for reaper. i need to do some digging to see if i can find that...

**Comment by timothyschoen** [comment]
I made some fixes that caused Ardour to crash on Windows, I'm hoping that will fix this as well... However, after trying a lot, I still cannot reproduce this. Could you try this version?

https://github.com/timothyschoen/PlugData/suites/7939471518/artifacts/338866385

**Comment by offthesky** [comment]
just tested, that latest build seems to have fixed the bug!

**Comment by timothyschoen** [comment]
Yay!
