### ISSUE TITLE
New line not possible in comment?

### ISSUE THREAD

**Issue by tmhglnd** [timothyschoen/PlugData#159]
Hi Tim,

First of all amazing work so far! I was playing around with the standalone and I noticed that the `comment` doesn't allow me to enter a new line. When hitting `return` it deselects the object. I tried other key combinations like `shift+enter` `ctrl+enter` etc. Just letting you know, it's not a major issue of course.

**Comment by timothyschoen** [comment]
Hi Timo! The Max classes at HKU are what got me interested in patching, so thanks for that.

The comments still need some work, there are a few problems. I thought newlines worked at some point, I must have accidentally broken that. Another big problem is that there are some size inconsistencies compared with pd-vanilla. I was planning to rewrite the comment after the coming release, I'll make sure newlines work.

**Comment by timothyschoen** [comment]
A problem in Pd-vanilla is that any newlines you put into a comment disappear after saving/loading. So for consistency, it might be better to not allow newlines at all.

**Comment by tmhglnd** [comment]
Yeah fair enough!
