### ISSUE TITLE
Packages installer doesn't work in macOS

### ISSUE THREAD

**Issue by Nek** [timothyschoen/PlugData#160]
Hello,

I'm on macOS Monterey 12.5.1.
M1-based laptop.
The package browser/installer doesn't work. It won't update the packages list, and when I enter something it can't find anything.

Is it expected behaviour for M1 macs?

**Comment by timothyschoen** [comment]
Hi!

Are you using the last release, or a more recent build? I recently rewrote that part, so that will probably be either the cause of your problems or the solution to your problems

It should work on M1 Mac, I usually work on that myself.

**Comment by Nek** [comment]
It's PlugData v0.5.3 downloaded from the releases page.

**Comment by timothyschoen** [comment]
Can you try this version?

https://github.com/timothyschoen/PlugData/suites/7939471518/artifacts/338866380

**Comment by Nek** [comment]
It seems to work! Huge thanks, both for the project itself and for the quick resolution 🥹
I guess the problem is gone for the next release.

**Comment by timothyschoen** [comment]
No problem! And that's great news, I'm glad the new system works.
