### ISSUE TITLE
macOS, another Deken issue

### ISSUE THREAD

**Issue by Nek** [timothyschoen/PlugData#161]
The problem happens with the HEAD build, I think.
I've started the app in Rosetta mode to be able to install externs not compatible with Apple Silicon architecture.
I'm getting an error message for any package I try to download.
Is it even possible to use Rosetta mode with externs?
<img width="710" alt="image" src="https://user-images.githubusercontent.com/132011/186224377-492a9a98-3a42-4bf2-9419-2e113d7d86bd.png">

**Comment by Nek** [comment]
And I've just checked, it works in vanilla version.

**Comment by timothyschoen** [comment]
Thanks for reporting, I can reproduce this! Some packages work (like ELSE, even though that's useless to install), but most don't. I'll see what's going on.

**Comment by timothyschoen** [comment]
There's a check to make sure the zipfile is not empty that returns a false positive here. I've removed the check, so it should work now.
