### ISSUE TITLE
opening expr help file freezes plugdata

### ISSUE THREAD

**Issue by porres** [timothyschoen/PlugData#168]
I'm using macOS

**Comment by timothyschoen** [comment]
Fixed! Very silly bug: it found the [expr] helpfile in multiple locations, and opened both. Which lead to so many clashing definitions that PlugData dies of console spam.

**Comment by timothyschoen** [comment]
I've made some more improvements to make sure this can't happen anymore.

1. If you open a patch that's already opened, it will not open it but will just show the tab. Similar to what pd-vanilla does. It prevents console spam
2. The console can now handle console spam, even at full audio rate. It puts the CPU usage at about 60% for me, which definitely slows it down a bit, but at least it doesn't freeze. The most intensive part is calculating how wide the text is, so it can wrap around correctly. I'm now using a rough estimate for that instead.
