### ISSUE TITLE
objects missing

### ISSUE THREAD

**Issue by porres** [timothyschoen/PlugData#170]
actually, according to the print scree in 

https://github.com/timothyschoen/PlugData/issues/167#issue-1349851838

I can confirm objects db2lin~, bicoeff2, route2, bitnormal~ and bl.imp2~ are actually missing

they don't create with or without the prefix and the autocomplete doesn't show them

**Comment by timothyschoen** [comment]
Thanks for reporting, I'll fix that.

**Comment by timothyschoen** [comment]
All added now!
