### ISSUE TITLE
bicoeff is not renamed to bicoeff2

### ISSUE THREAD

**Issue by porres** [timothyschoen/PlugData#171]
bicoeff is now a gui object but plugdata still has the old bicoeff object, which was renamed to bicoeff2 (so the new bicoeff is actually missing as well as bicoeff2 in practice)

**Comment by porres** [comment]
related to https://github.com/timothyschoen/PlugData/issues/170

**Comment by timothyschoen** [comment]
Hmm looks like I overlooked a whole bunch of stuff... I'll probably create a v0.6.1 soon with urgent fixes.

**Comment by timothyschoen** [comment]
Done!
