### ISSUE TITLE
A few PlugData 0.6.0 issues

### ISSUE THREAD

**Issue by 60-hz** [timothyschoen/PlugData#176]
- [x] Trying to insert an object which doesn't have outlet (using shift key) lead to a crash
- [x] Double click to edit message box always put the cursor at beginning (left), cannot edit in the middle like objects box
- [x] help files cannot be found for externals downloaded with Deken package manager
- [x] number / nbx boxes : up/down key doesn’t make any output (behave like a « set » method)
- [x] number / nbx boxes : Sliding with mouse returns repeated outputs, should make only output for every new value
- [x] Inserting object between works well, using shift + move could also disconnect box from coords?
- [ ] In dark mode, all atoms boxes switch to black, for consistencies with other gui’s, they should also keep in grey.
- [x] Naming new object box to [hslider] or [vslider] make them with no UI theme (black/white).
- [ ] Atom boxes could expand while typing in action mode like message box do in edit mode?

Tested on MacOS 12.2.1

**Comment by timothyschoen** [comment]
Thanks for reporting, will take care of these.

The reason atom objects change along with the theme and the other objects don't is because atoms don't have colour settings. So I think it would make sense to just theme them along with the rest of the app.

**Comment by timothyschoen** [comment]
Removing an object from a connection comes with many more edge cases. I'm planning to release v0.6.1 pretty soon, with the most important bugs from v0.6.0 fixed, so it will probably be implemented for v0.6.2.

**Comment by timothyschoen** [comment]
There are 2 points left:

The atom problem is impossible to resolve because I can't save the colour in the patch (there's no colour field I can use for it).

Resize-while-typing for atom boxes is also something I'm not sure about, because it violates the rule that the patch can't be changed in lock mode, which I think is a pretty good thing to keep.

Other than that It's all done!
