### ISSUE TITLE
subpatches sometimes load empty

### ISSUE THREAD

**Issue by offthesky** [timothyschoen/PlugData#178]
when i copy paste the one-off subpatch code within the attach patch, and then save/reload the project, that copied subpatch loads empty.
steps: 
1 open reaper with blank project
2 load plugdata vsti or vst
3 load the attached patch
4 select a subpatch (and any comment boxes associated with it)
5 paste
6 save the reaper project
7 reload. observe the subpatch is empty
note: you can also just copy/paste the plugin instance to observe the subpatch not loading in the pasted plugin instance

tested with 0.6.0 32b/64b reaper v6.66

[dc to midi note.zip](https://github.com/timothyschoen/PlugData/files/9435847/dc.to.midi.note.zip)

**Comment by offthesky** [comment]
https://user-images.githubusercontent.com/95579081/186975918-71cf97e5-1532-4c1e-9bbe-479f3c614558.mp4

**Comment by offthesky** [comment]
https://user-images.githubusercontent.com/95579081/186977014-7b8fde54-5396-4c5b-9c18-ee64321b8939.mp4

**Comment by timothyschoen** [comment]
I can reproduce this, this is very strange! It gets even weirder: if you clear out the entire patch except for 1 pd2vol object, that copy/paste that, it does work normally. I'm trying to find what causes this but I'm not sure.

**Comment by timothyschoen** [comment]
Found the problem! I made a small mistake somewhere, that caused subpatchers to be seen as abstractions by Pd. All fixed now!
