### ISSUE TITLE
params no worky

### ISSUE THREAD

**Issue by offthesky** [timothyschoen/PlugData#183]
both the vsti and vst, via CMake #1206: Commit [9de5e2b](https://github.com/timothyschoen/PlugData/commit/9de5e2b4bb03091e2189785cbf07ff0bfce9e3af)

ive only been able to test in 32bit reaper

steps to repro: hit the + next to a param, add a number box after it. start moving the param slider in the ui. no data comes through.

**Comment by offthesky** [comment]
update: got it to work again by deleting the roaming/plugdata folder then reloaded the plugin and it rebuilt the plugdata folder. guessing something old just wasnt getting flushed out when installing this latest version.

**Comment by timothyschoen** [comment]
This is a known problem, unfortunately there’s not much I can do about it. I messed something up last release, so now you have to trash PlugData’s folder. On Windows this is necessary, but on Mac and Linux it’s also recommended. The reason I don’t want to remove this folder programmatically is that the user might have patches stored there (or modified ELSE’s abstractions), which I don’t want to overwrite.

 Hopefully I’ve fixed everything this time, and we’ll have a smoother update process next time.
