### ISSUE TITLE
Cannot open or save patches via Ardour

### ISSUE THREAD

**Issue by hellocatfood** [timothyschoen/PlugData#189]
I'm running Ardour 6.9 and have loaded the plugdata vst and now trying to load an existing patch by clicking the open icon. Unfortunately the dialogue box doesn't appear and so I'm not able to open an existing patch.

The same applies when trying to save a patch: the dialogue box doesn't appear.

I'm using Ardour 6.9 on Ubuntu 22.04. The error happens when using both Wayland and X11

**Comment by davidhealey** [comment]
Hello, 

If you set this JUCE flag before building it should work `JUCE_DISABLE_NATIVE_FILECHOOSERS=1`

**Comment by timothyschoen** [comment]
There's an option "Use native dialogs" in the settings menu now, so you can disable the native menu in case they don't work.

**Comment by bapch** [comment]
I'm running Ardour 7.2 and 7.3 with Linux Mint/Wayland.
I can set "use native dialogs" to "yes", but i still can't open or save patches. Upon reopening the settings panel, the option is still set to "no". Is there a way to set the option by modifying a settings file ?

**Comment by timothyschoen** [comment]
> I'm running Ardour 7.2 and 7.3 with Linux Mint/Wayland. I can set "use native dialogs" to "yes", but i still can't open or save patches. Upon reopening the settings panel, the option is still set to "no". Is there a way to set the option by modifying a settings file ?

Whoops, that's a bug. The "system dialog" property is assigned to the "tail length" setting, it's very good you caught this!

It should be fixed after c79d50241bca95ab2a0105c2f8f6b76e8ab98afb
