### ISSUE TITLE
Installed on Mac OS X 12.1 - no files anywhere, but lost 20GB of space

### ISSUE THREAD

**Issue by kirkmarkarian** [timothyschoen/PlugData#19]
Anywhere I can find these files - help a non-programmer.  I can find hidden folders, just don't know where these files are.

**Comment by timothyschoen** [comment]
Hmm that strange. It unpacks some files (settings, externals and help files) to _~/Library/PlugData_ on MacOS

But that should never be 20gb! Let me know if it really is 20gb, because then something is going horribly wrong.

Did you use the last release or did you build from source? If you built from source, there is a chance that there are some Xcode cache files left behind, I think rebooting would take care of that.

**Comment by kirkmarkarian** [comment]
Thanks for the quick reply!  I installed it via the code on the GitHub page:

git clone --recursive https://github.com/timothyschoen/PlugData.git
cd PlugData
mkdir build && cd build
cmake .. (the generator can be specified using -G"Unix Makefiles", -G"XCode" or -G"Visual Studio 16 2019" -A x64)
cmake --build .

I should check for Xcode - I have had issues with that particular app's files before.  The odd thing was that it also ended up on my little SD card as well.  I went from  35GB down to 14GB.  There's a possibility I may have flubbed up somewhere else, but I only just noticed it after I did this install.  I'll keep searching, because I enjoy looking for these things and learning the guts of OS X!

**Comment by timothyschoen** [comment]
I believe there are storage analysis tools for MacOS that can tell you exactly where the biggest files and folders are, that might be of use. One's called GrandPerspective.

Did you move the plugin files to the VST and Component search paths after building? It doesn't do that automatically, I should probably add it to the build description.

**Comment by kirkmarkarian** [comment]
Ah, no - to moving the files.  That's because I've no clue where they would be.  Once I figure out this initial issue, I'll try this again.  Where would they be stored?  I'll also check out GrandPerspective.

**Comment by timothyschoen** [comment]
AU:     ~/Library/Audio/Plug-Ins/Components/
VST3: ~/Library/Audio/Plug-Ins/VST3/

~ btw is short for /Users/yourname, I don't know how familiar you are with Mac/Linux

**Comment by kirkmarkarian** [comment]
Yep, I get that - I checked those out - nothing there.  I'll try again, this time with the actual pre-release package :) 

Thanks for your help!
