### ISSUE TITLE
Minimum and maximum range of numberbox has no effect!

### ISSUE THREAD

**Issue by jaffasplaffa** [timothyschoen/PlugData#190]
Hello :) 

Installed 0.6.1 today and it seems like the minimum and maximum settings for the numberbox does not work.

Pretty easy to recreate:
1. Create a numberbox
2. Set a minimum and maximum range.
3. Lock the patch and try setting a value outside the range.
4. The value of the set range will still be set, the min/max has no effect.

I did also try my 0.5.1 install of Plugdata and the min/max works in that version.

Best wishes, 
Jakob

**Comment by timothyschoen** [comment]
Thanks for reporting! It seems I'm not able to stop breaking stuff constantly...

**Comment by timothyschoen** [comment]
Fixed!
