### ISSUE TITLE
abstractions don't work as intended compared to pure data

### ISSUE THREAD

**Issue by Apep-the-snek** [timothyschoen/PlugData#194]
when right clicking on the work area in a patch and click properties, what happens in pure data is that a menu shows up where you can select graph on parent, and you can set the size of the abstraction object as well as range, on the experimental build on the AUR i can do everything except set the size of the abstraction object (how it appears in other patches) which is what i need, i tested this on stable and i can't even set the ranges there. is there a hotfix for this? also please fix this.

**Comment by Apep-the-snek** [comment]
oops, when i say version 0.2 and 0.90 i mean the AUR versions. i would assume the same issues are in the github versions, which easy to test for, just right click and select properties, and you see my issue (if not, then i need to migrate to the github versioin).

**Comment by timothyschoen** [comment]
You can do this by opening the abstraction and moving the blue rectangle around. I might add it to the properties panel too, I'll consider that.

**Comment by timothyschoen** [comment]
Closing this issue because there is a way to do this currently. I might still implement another way to do it at some point.
