### ISSUE TITLE
play.file~ crash when changing channel count

### ISSUE THREAD

**Issue by 8ouble-r** [timothyschoen/PlugData#20]
I was getting a lot of crashes when testing out _play.file~_
I think it might be due to changing the referenced file to another that had a different channel count. e.g. if the object originally had a stereo file and had both L/R connections to the _dac~_, then the file was changed to a mono one, it would crash the host.

I could also replicate this when the object was just _play.file~ 2_ (for 2 channels that were connected to the dac) and then I changed it to _play.file~ 1_

[Crash log for Reaper](https://drive.google.com/file/d/1u9q7DBvqnCtchb4i4FrHV9-lMJRFp_W9/view?usp=sharing).

**Comment by 8ouble-r** [comment]
This crash is no longer occurring in v0.3

**Comment by timothyschoen** [comment]
That's a nice surprise, I'm actually not sure how this got fixed
