### ISSUE TITLE
[windows] Standalone installs to C: despite choosing a different partition

### ISSUE THREAD

**Issue by jamshark70** [timothyschoen/PlugData#202]
Win64, using the latest .exe installer from release assets (PlugData 0.6.2).

1. Run the installer.
2. Choose `D:\Program Files\PlugData` as the install location.

After this, I have uninstallers at D:\Program Files\PlugData, but PlugData.exe and the dll are at C:\Program Files\PlugData.

The start menu shortcut points to D: and thereby does not find the executable.

**Comment by timothyschoen** [comment]
Hi jamshark, 

Thanks for reporting, I'll have a look at this!

**Comment by timothyschoen** [comment]
I can fix it for the standalone, but the plugins will still be installed to wherever your normal Program Files folder is located. I'm not sure if there's anything I can do about that. But this will at least fix the shortcut problem.

**Comment by timothyschoen** [comment]
I also wonder: I am never prompted to enter an install location. Are you?

**Comment by jamshark70** [comment]
> the plugins will still be installed to wherever your normal Program Files folder is located

Agreed, plugins should go in the standard plugin search paths.

> I am never prompted to enter an install location. Are you?

I was -- odd.

**Comment by timothyschoen** [comment]
I think this is fixed, but it's hard for me to confirm that because it never prompts me for an install location.

Could you try a recent Github Actions build, like this one: https://github.com/timothyschoen/PlugData/actions/runs/3404582988, to see if it works now?

**Comment by timothyschoen** [comment]
I've switched to a better installer, so this should be solved.

**Comment by jamshark70** [comment]
Great, thanks!
