### ISSUE TITLE
Command + t crashes the app while on welcome screen

### ISSUE THREAD

**Issue by JochemVanIterson** [timothyschoen/PlugData#206]
When I press command + t (command to open a new tab) while on the welcome screen, the (standalone) app crashes. When I first click the 'new patch' button, or open an existing one the command works as it should!

**Comment by JochemVanIterson** [comment]
I work on a macbook pro 2021 with a m1 pro cpu and macos 12.6 by the way

**Comment by timothyschoen** [comment]
Hi Jochem, thanks for reporting!

I can reproduce this, fix coming in a few minutes

**Comment by JochemVanIterson** [comment]
Thanks!!

**Comment by timothyschoen** [comment]
Done in cecdcaa!
