### ISSUE TITLE
Certain objects have strange object args editing behavior

### ISSUE THREAD

**Issue by Yzrsah** [timothyschoen/PlugData#208]
Depending on the class that is typed into the object box, certain objects' object argument fields don't work with the mouse in the canvas editor. For example if I create an object `pd foo` or `plate.rev~ 10 0.1 0.1 0.1` and then try to edit the object arguments, I can't move the cursor position by clicking, I can only use the keyboard.

**Comment by timothyschoen** [comment]
Aha, I think this is a problem for all subpatchers/abstractions. Will fix this very soon!

**Comment by timothyschoen** [comment]
Fixed with 97c0831
