### ISSUE TITLE
PlugData can't find help files for [bonk~] [sigmund~] and [fiddle~]

### ISSUE THREAD

**Issue by alfonso73** [timothyschoen/PlugData#209]
Hi!
Checking latest "action" version i noticed that PlugData can't find help files for [bonk~] [sigmund~] and [fiddle~].
It's the first time i check for help files for this externals so i don't know if it's a regression or has always been like this.
best!

**Comment by timothyschoen** [comment]
Should be fixed, though you'll actually see this once I'll bump the version number (or if you remove PlugData's config folder)
