### ISSUE TITLE
Sidebar resizes while dragging its scroll bar

### ISSUE THREAD

**Issue by Yzrsah** [timothyschoen/PlugData#210]
- While trying to use the scrollbar to scroll up and down in the documentation browser, the sidebar resizes if I move my mouse to the left or right by any pixels. There's no area of the scrollbar I'm able to grab which does not resize the sidebar.

- My sidebar kept resizing by a few pixels then I realized it was happening while clicking on the triangles in the documentation browser. While pressing the triangles to expand/close the folders of the documentation browser, the side bar also resizes.

**Comment by timothyschoen** [comment]
Thanks for reporting, fixed it with 045e5575e3ddb697d6f3442abb4e1779cb4ce487
