### ISSUE TITLE
Else's [samps2ms] doesn't work

### ISSUE THREAD

**Issue by alfonso73** [timothyschoen/PlugData#211]
Hi!
[samps2ms] issues a "....couldn't create" output in PlugData console.
Since it's an abstraction going insite it the [nbang 1] object is outlined in red.

**Comment by timothyschoen** [comment]
Strange, I can't reproduce this. 

You could try this: 
1. Close PlugData
2. Remove C:\Users\timschoen\AppData\Roaming\PlugData\0.6.2
3. Reopen PlugData

See if it works then

**Comment by alfonso73** [comment]
Yep. I've got a lot of garbage from older PlugData versions in C:\Users\your_name\AppData\Roaming\PlugData\. Now it works! thanks

**Comment by timothyschoen** [comment]
Yeah I should fix a better way to handle that... Glad it's fixed!
