### ISSUE TITLE
Can't send edit method to graph arrays

### ISSUE THREAD

**Issue by alfonso73** [timothyschoen/PlugData#212]
Hi! I'd like to protect my graph arrays from mouse editing but sending to an array called "test" an 
;
test edit 0

message does not work. I can still edit the graph with the mouse

**Comment by timothyschoen** [comment]
I didn't know this feature of Pd existed, thanks for enlightening me. Fortunately I was just working on a feature that will make this possible to implement!

**Comment by alfonso73** [comment]
You can find all in canvas-help.pd and in the [pd reference] on top right of canvas-help.pd

**Comment by timothyschoen** [comment]
Fixed!
