### ISSUE TITLE
Some GUI issue in Settings and a request for font size

### ISSUE THREAD

**Issue by alfonso73** [timothyschoen/PlugData#215]
Hi. This happens if i select the actual entry line in the search path tab in Settings

![image](https://user-images.githubusercontent.com/3230434/200546709-cf183837-c0d6-4656-be88-0cd8517a5830.png)

Would be great to get an option for font size.

**Comment by timothyschoen** [comment]
Same solution as the transparency problem, reset the colour settings ;)

I'll make sure the transition goes smoothly once the version comes out!

**Comment by alfonso73** [comment]
This one is not fixed by resetting the colour setting
