### ISSUE TITLE
Some transparency issues

### ISSUE THREAD

**Issue by alfonso73** [timothyschoen/PlugData#216]
Some transparency issues...

![image](https://user-images.githubusercontent.com/3230434/200547260-746d9b2c-9ff8-4343-9a72-a5ca3bcf9184.png)

**Comment by timothyschoen** [comment]
Hi! I see you're using a recent build, if you go to Settings->Theme->Reset it should work again. I've added a few new colours you can modify, I still have to make sure the transition from v0.6.2 works correctly. Right now, it can't find the settings for that colour, and it becomes transparent instead.

**Comment by timothyschoen** [comment]
This problem is gone now :)
