### ISSUE TITLE
Some common shortcuts

### ISSUE THREAD

**Issue by Yzrsah** [timothyschoen/PlugData#218]
These three would be very helpful

- Shift+click on one object in a multi selection to deselect it

- Ctrl+click on background to lock/unlock patcher

- Alt+drag object or selection to drag a duplicate

The alt modifier is already taken up by opening Help so maybe drag duplicate should be Ctrl+alt instead. But I think Alt is better for drag duplicate because opening Help does not require a modifier and is not downgraded too much by being in the right click menu, whereas the drag duplicate functionality requires a keyboard modifier to drag the duplicate to the new position quickly.

**Comment by timothyschoen** [comment]
Hi, I agree with all of these, I'll look into it! I tried to implement better select/deselect behaviour before, but I got stuck because the selection logic in PlugData has gotten a bit too complex, so that needs to be cleaned up as well.

Those other too are very doable, @Nejrup, you might find this interesting to work on, if you have time.

And you can check if there was any dragging on mouseUp, to decide whether or not the helpfile should be opened, I think Max does the same.

**Comment by Nejrup** [comment]
@timothyschoen hadn't seen this, but I did exactly that:)
I've fixed Alt + drag so it will now duplicate & help file will open at Alt + mouseup if no dragging happened

**Comment by timothyschoen** [comment]
I think @Nejrup has fixed all of these now (thank you so much!), so I'll close this :)

**Comment by Yzrsah** [comment]
@timothyschoen @Nejrup this is fabulous, thanks guys. The new version is getting so much better!

@Nejrup there is some bug with Alt-drag - while dragging, the dragged object is invisible because it's offset offscreen into negative coordinates. After the drag is completed the canvas gets offset into negatives and the Object-number helpers are stuck, after pressing undo there's a double undo entry.

![](https://i.imgur.com/mTY92aG.png)

**Comment by Nejrup** [comment]
Yes, there was a conflict with the snapping feature & this.. but both should work now :) I also implemented the single undo action. Try it out: d2f38198f6f4b41da1bbe2a131a8688ace0e14c4

**Comment by Yzrsah** [comment]
@Nejrup It's working nicely. There's a little bug, the Object-number helpers stay stuck after the drag is finished.

![Stuck](https://i.imgur.com/BCrnchT.gif)
