### ISSUE TITLE
Toolbar Icon Sizing Too Small

### ISSUE THREAD

**Issue by 8ouble-r** [timothyschoen/PlugData#23]
Thank you for the improvements in 0.3. But I think the smaller toolbar icons are now too small - you lose the details of the icon.

I agree reducing the toolbar height is a good change, but there is actually room to increase the overall size of the icon in the current toolbar height e.g. there is blank space above all the icons.

I also think some of the horizontal space/gaps between the icons could be reduced a bit.

**Comment by timothyschoen** [comment]
Agreed, the space gaps are definitely too much right now! I'll also increase the height just a bit so we have a better middle ground between space usage and being able to see the icons.

**Comment by timothyschoen** [comment]
Toolbar height is still the same, but I made the icons bigger. Also made the statusbar a bit bigger because those icons were very small.
