### ISSUE TITLE
Ubuntu .dep package does not include the VST and LV2 plugins

### ISSUE THREAD

**Issue by robysweettrip** [timothyschoen/PlugData#232]
Hello,

I noticed that the `.dep` file in [the Ubuntu repository](https://software.opensuse.org//download.html?project=home%3Aplugdata&package=plugdata) does not include, and therefore, install the VST3 and LV2 plugins. 

![image](https://user-images.githubusercontent.com/107824400/202544537-b9379345-91e2-4137-8ff3-17139e9bf31f.png)

**Comment by timothyschoen** [comment]
Hi, there are separate packages for the VST3 and LV2 plugin, called PlugData-vst3 and PlugData-lv2.

**Comment by robysweettrip** [comment]
That what I use. That said, it may be helpful to update the `READ.ME` to mention what the `.dep` includes or not to minimize confusion :)

**Comment by timothyschoen** [comment]
I've made the installation description in the readme more complete and clear, thanks for the sugggestion!
