### ISSUE TITLE
Audio Output Meter Redraw Issue

### ISSUE THREAD

**Issue by 8ouble-r** [timothyschoen/PlugData#24]
Since 0.3 the audio output meters at the bottom of the plugin do not redraw/refresh correctly, particularly if the audio going into PlugData stops e.g. if I'm using PlugData as a guitar effect and stop playing (no audio to the plugin) then the meters will freeze and not fall back to zero.

The same is true if I play an audio file from PlugData - the meter will freeze once the file stops playing.

If this is part of a change to reduce CPU (which is good!) then I would consider removing the meters altogether, as they are not useful at all when not updating correctly.

**Comment by timothyschoen** [comment]
Thanks for reporting! The idea was indeed to reduce CPU usage. I'll make sure they update correctly, it shouldn't be too hard to figure out.

**Comment by timothyschoen** [comment]
Should be fixed!
