### ISSUE TITLE
Gem is not working properly

### ISSUE THREAD

**Issue by Earell** [timothyschoen/PlugData#245]
In PlugData 0.6.2 on Windows, opening a Gem window create an error displayed in the console : GL[1282]: invalid operation. That makes me unable to change the values and having the result displayed. I have to close and reopen the Gem window to see it. I tested the same code in PureData and it works properly.

**Comment by timothyschoen** [comment]
Hi! This is a known issue:

https://github.com/timothyschoen/PlugData/issues/182
