### ISSUE TITLE
Log/Print message display issue

### ISSUE THREAD

**Issue by 8ouble-r** [timothyschoen/PlugData#25]
When you have autoscroll enabled and the log/print messages fill up the list and it starts scrolling - the most recent message will not display at the bottom of the list, until:
1. You resize the window, or
2. Another message is printed and the earlier one will then show up

**Comment by timothyschoen** [comment]
Whoops, I overlooked that. Should be a quick fix!

**Comment by timothyschoen** [comment]
This is fixed now!
