### ISSUE TITLE
credits

### ISSUE THREAD

**Issue by porres** [timothyschoen/PlugData#3]
hi, nice work, is this based on https://github.com/porres/Camomile-ELSE? If so, can you give me and @emviveros credits as well? cheers

**Comment by timothyschoen** [comment]
Whoops I forgot, you're in there now!

**Comment by porres** [comment]
Hi, please note credits for ELSE is mine, but @emviveros takes care of  on the 'Camomile-ELSE' branch, which I think you are using as the basis of this project, right? We need to clear this out in the credits and info. https://github.com/porres/Camomile-ELSE

**Comment by timothyschoen** [comment]
https://github.com/porres/pd-else/issues/1128
https://github.com/porres/pd-else/issues/1127

You've already fixed these for ELSE, but they're probably still in Camomile-ELSE. Should be quick fixes.

**Comment by porres** [comment]
I used the release version

**Comment by porres** [comment]
it's also crashing in audacity :/ have you had a successful test in macOS? which version and which software?

**Comment by timothyschoen** [comment]
I think I've put the release up a bit too soon, I've found quite a few new bugs since then. I also realised I forgot to codesign my macOS release, that doesn't help. I'll put a new release up very soon, when I'm a bit more certain that it's going to work.

The last commit should probably work if you build it yourself. I've tested it on Monterey, in Logic, Reaper and Bitwig.

**Comment by timothyschoen** [comment]
The release version does work for me in Ableton 10 (both VST3 and AU), which is strange. I did upload a small hot fix two days ago, perhaps you downloaded it before that? If that's the case then it's hopefully already fixed

**Comment by porres** [comment]
no, i downloaded yesterday

**Comment by timothyschoen** [comment]
I've uploaded a new release which for minimum macOS version 10.11, that should fix it
