### ISSUE TITLE
[Feature Request] Infinite mouse drag

### ISSUE THREAD

**Issue by ludnny** [timothyschoen/PlugData#37]
Hi!

It's sometimes frustrating to be locked by the top or bottom of the screen when dragging a value in a number box.

![30](https://user-images.githubusercontent.com/46849877/155023348-4765b772-b9be-4b11-ad26-ce1f3dc2ee0b.gif)
 
I like the way [VVVV Gamma](https://visualprogramming.net/) for example manages it:
the mouse cursor disappears when dragging, and stays at the same position when reapearing. 
![31](https://user-images.githubusercontent.com/46849877/155029272-d87baa29-fe60-46fd-99b7-3bb1f4ea10ee.gif)
Far more natural when playing music!

**Comment by timothyschoen** [comment]
I assume you're using the last release version? I think I've already fixed this in the latest commit, by copying the behaviour from [Kiwi](https://github.com/Musicoll/Kiwi)

**Comment by ludnny** [comment]
Sorry I didn't mention it: the screenshot is from PlugData-Win64-v0.3.2

**Comment by ludnny** [comment]
I just tried with Kiwi, yes, that would be nice to have it in the next release!
Thank you for the great work

**Comment by 60-hz** [comment]
Another cool incredible patching project!
https://github.com/Fr0stbyteR/jspatcher

**Comment by timothyschoen** [comment]
That looks a lot like Max, cool project. Kiwi is more relevant for me because it's also made with JUCE and looks very nice, whenever I want to implement some kind of patching behaviour, it's a good reference to use. But always good to know what else is out there!

**Comment by ludnny** [comment]
Unfortunately it doesn't work in PlugData 0.5 Win64

**Comment by timothyschoen** [comment]
This is completely fixed now!

**Comment by timothyschoen** [comment]
Oh no! Thanks for letting me know, this is also the case on other platforms... It's strange because afaik I do the same things as Kiwi now, except it works there but not here. Probably missed something.

**Comment by timothyschoen** [comment]
Okay now it's actually infinite!
