### ISSUE TITLE
Crash when saving aupresets in Logic

### ISSUE THREAD

**Issue by armandvedel** [timothyschoen/PlugData#43]
When trying to save a preset in Logic's preset system the entire application crashes. Saving a pd file works however. I'm running Logic on M1 in Monterey.

**Comment by timothyschoen** [comment]
Thanks for reporting, I'll check it out. I hadn't really tested the presets yet I must admit, I've been too busy with other bugs and features. I'm also on M1 Monterey, so it should be easy to reproduce.

**Comment by timothyschoen** [comment]
Fixed in the latest commit! I'll release a new version soon when I finish fixing some other problems!

**Comment by armandvedel** [comment]
Wow!!
