### ISSUE TITLE
Set default volume to 1

### ISSUE THREAD

**Issue by armandvedel** [timothyschoen/PlugData#44]
I tried to send a signal from one instance of PlugData to another by passing it from the dac~ of the first to an adc~ in the second. The value in the second instance (i.e. after the adc~), is slightly lower. In testing it, i tried it with a fixed value and sig~ and it still seems to happen.

**Comment by timothyschoen** [comment]
The default volume is 0.75 right now, so make sure you open the volume all the way. I should probably make 1 the default, to prevent problems like this.

**Comment by armandvedel** [comment]
Doh! Thanks for the quick reply

**Comment by timothyschoen** [comment]
fixed on latest commit
