### ISSUE TITLE
ld error when linking target in Arch

### ISSUE THREAD

**Issue by aik2mlj** [timothyschoen/PlugData#45]
```
/usr/bin/ld: Error: unable to disambiguate: -Symbolic (did you mean --Symbolic ?)
```

I guess it's because of the change at CMakeLists.txt:20 in [this commit](https://github.com/timothyschoen/PlugData/commit/a94c692a5dc5a8526e5efa209bf36bb9192a14f9). Please take a look.

**Comment by timothyschoen** [comment]
That must be a mistake, I don't remember changing that line. Fix coming later today!

**Comment by timothyschoen** [comment]
it should be fixed, is it working for you now?

**Comment by aik2mlj** [comment]
Yep!

**Comment by timothyschoen** [comment]
@aik2mlj Could you add 'aarch64' as a supported architecture on AUR?

**Comment by aik2mlj** [comment]
ok sure!
