### ISSUE TITLE
Short cuts/key commands?

### ISSUE THREAD

**Issue by jaffasplaffa** [timothyschoen/PlugData#48]
Hey :) 

Great project you have going here. I am a big fan of anything Pure Data related, especially projects that make it easier to use with other music software, like a DAW :) 

Just wanted to swing this by you. I am not able to use short cuts/key commands. Maybe I am not doing it right, but usually in PD on Mac, you can use command+number to add different object, like an empty object(command+1) or command+2, which creates a message.

Is that something you plan on implementing?

Best wishes,
Jakob

**Comment by timothyschoen** [comment]
Hi!

The default shortcuts are Max-like, so 'n' for new object, 's' for slider, 'f' for floatatom etc. You can change the shortcuts in the settings dialog, under the keyboard tab.

Good luck patching!

**Comment by jaffasplaffa** [comment]
Ahhh, completely missed the sub tabs :) 

I see, I can change them to what I'd like, that's nice ;) 

Thanks!

**Comment by timothyschoen** [comment]
No problem, maybe I should highlight the selected tab more clearly so the tab behaviour is more obvious?

**Comment by jaffasplaffa** [comment]
Now that I know, it's all good. Maybe I just missed the obvious.

But in some way, yeah, for beginners like myself, it would probably be good to make it easier to find/see :)
