### ISSUE TITLE
A question about PD compatibility

### ISSUE THREAD

**Issue by carlca** [timothyschoen/PlugData#5]
In an attempt to learn more about PureData, I've gone to the main website at https://puredata.info. There, I find that there are four different flavours of PD....
* Pd-vanilla
* Pd-ceammc
* Pd-L2Ork
* Purr Data

Which of these is the implementation contained in PlugData the closest to? I just want to make sure that I don't go following the wrong path and find myself in a frustrating muddle of incompatibilities.

**Comment by timothyschoen** [comment]
It's closest to Pd-vanilla, but it extends it with a lot of externals from the ELSE library
