### ISSUE TITLE
Bottom bar doesn't appear when fullscreen

### ISSUE THREAD

**Issue by ludnny** [timothyschoen/PlugData#50]
Hello, 

The bottom bar doesn't appear when fullscreen in PlugData release 0.4.2 Win64 Standalone 

In Windowed mode, no problem:
![image](https://user-images.githubusercontent.com/46849877/162155236-72c8de8f-22b5-4802-9f1b-d88855e3360b.png)

In Fullscreen mode, after clicking the + button top right (screen resolution is 1920x1080px), no bottom bar:
![image](https://user-images.githubusercontent.com/46849877/162155583-6053d624-a3ae-4ccd-ab2a-1fea8f253976.png)

**Comment by timothyschoen** [comment]
Thanks for reporting, I'll check it out!

**Comment by timothyschoen** [comment]
I had rewritten the fullscreen function to work around a JUCE bug. That bug has been fixed by now, so I've reverted to JUCE's normal fullscreen behaviour which fixed this bug.

**Comment by ludnny** [comment]
Works in 0.5 Win64 :)
