### ISSUE TITLE
[Standalone 0.4.2] New project crush the current one

### ISSUE THREAD

**Issue by FlachyJoe** [timothyschoen/PlugData#52]
Hi,
clicking on the _New project_ icon crush the current file instead of opening a new tab. On linux at least.

**Comment by timothyschoen** [comment]
I'm aware of this, it's not really ideal. Right now, you can only have one root patch per window. There's no reason for this, I'll write a better mechanism soon!

**Comment by timothyschoen** [comment]
Should be fixed!
