### ISSUE TITLE
Externals are broken on Windows

### ISSUE THREAD

**Issue by timothyschoen** [timothyschoen/PlugData#53]
<img width="552" alt="Screenshot 2022-04-08 at 17 27 22" src="https://user-images.githubusercontent.com/44585538/162473805-fc19f62e-31e3-47a6-9eba-1bfe3c45724a.png">

When trying to load externals on Windows, you get this error.

**Comment by porres** [comment]
can we use now any external packages in PlugData?

**Comment by porres** [comment]
please, why are you testing 'nilwind'? :)

**Comment by timothyschoen** [comment]
I kinda picked nilwind randomly from deken to do testing, after all I couldn't pick cyclone or ELSE because they are already included :)

On Linux and MacOS externals downloaded from deken or elsewhere should work. On Windows, there's still a problem. I need to seperate the libpd.dll from the executable in order for externals to work. But that means I need to create an installer to create a folder in Program Files, and also need to drastically change my build system.

This is made worse by the fact that my Windows PC is very slow, and I don't have much experience on Windows. I'll fix this at some point, probably by the time I'm going to make installers for most platforms. If anyone with more windows development experience can help out, let me know!

**Comment by timothyschoen** [comment]
I see you're close to releasing a stable version of ELSE (congrats!), I'll make sure to update it when it's ready!

**Comment by porres** [comment]
well, cool, but it would seem pointless to ship ELSE if anyone can just install it, right?

plese forget about nilwind :) it's a lie what they say

**Comment by alfonso73** [comment]
> well, cool, but it would seem pointless to ship ELSE if anyone can just install it, right?
@porres i guess @timothyschoen has to include ELSE for the plugin version of PlugData to work...the same way as with Camomile...

**Comment by timothyschoen** [comment]
@alfonso73 is correct, that will remain an issue because of the way pd externals are designed.

Besides, there are certain ELSE objects like keyboard that I've written GUI wrappers for, and I'm planning to do that for even more objects (pic at least, and more if needed). Externals are also still broken on Windows.

The fact that we can't use externals with the PDINSTANCE flag sucks, but since all externals rely on global variables that don't exists with the PDINSTANCE flag (they're wrapped now in a struct) there's almost no way around this. The only way I could imagine would be messing with the linker to make it point to the correct PDINSTANCE variables, I don't think that is possible though.

**Comment by alfonso73** [comment]
@timothyschoen surely not being able to load dynamically externals in plugin versions of PlugData (and in Windows standalone version) is a great disadvantage because externals are a great resource for a modular enviroment as Pd actually is. Is the same limitation Camomile has. But given the great work done by @porres with ELSE i think that with ELSE included PlugData and Camomile will have pretty much everything needed for a DAW use of Pd. I'd just add faustgen~ and a good set of bandlimited oscillators externals (BLIT, minBLEP, polyBLEP or whatever) to the externals "embedded" in PlugData (and Camomile...even if Camomile doesn't seems so actively developed in the last year).

**Comment by timothyschoen** [comment]
So.. I'm probably missing something here but I've added global variables for "s_float", "s_bang" etc. and now externals can load with PDINSTANCE enabled...

I'm not fully aware what these variables do to be honest. I see that the s_symbol part is just constantly set to "float" for s_float. I feel like there must be more going on, but so far I'm getting very normal behaviour out of externals I've tried (and I'm not even initialising these variables yet!)

@porres Do you know what exactly the purpose is of these global s_ variables? It's pretty much just these variables that are getting in the way of having normal externals support with PDINSTANCE enabled.

**Comment by porres** [comment]
> @porres Do you know what exactly the purpose is of these global s_ variables?

nope

**Comment by timothyschoen** [comment]
Externals on Windows work now!! It was a big hassle, but the action now generates an installer for Windows which will also install pd.dll into PlugData's path, making externals on Windows finally work! I'm still working on things, but it works in 5556e4efab6b0b9e7e8e8c168539b6ca1ec9cf62 for example. Next release will have full external support for Windows.

An installer for Mac is also in the works, because copying all these plugin formats for each update is annoying.

**Comment by timothyschoen** [comment]
<img width="898" alt="Screenshot 2022-07-06 at 02 48 52" src="https://user-images.githubusercontent.com/44585538/177439766-809ce2a7-46e0-4ef5-b243-d26fb0cdbcd6.png">

Proof
