### ISSUE TITLE
Toggle - change on mouse-up

### ISSUE THREAD

**Issue by ludnny** [timothyschoen/PlugData#55]
Hi!

When clicking on a Toggle, the state changes only when the mouse button is released. 
The expected behaviour (the behaviour of Bangs in PlugData or of Toggles in Max) should be: the state changes directly when the mouse button is pressed. 

Tested with 4.0.2 on Standalone Win64

**Comment by timothyschoen** [comment]
I'm aware of this but it's nice to be reminded. Should be simple to fix!

**Comment by ludnny** [comment]
Works in 0.5, thanks!
