### ISSUE TITLE
Feature request: one-click and drag activation

### ISSUE THREAD

**Issue by ludnny** [timothyschoen/PlugData#56]
- Ability to activate a serie of Toggles or Bangs in one click+drag

![32](https://user-images.githubusercontent.com/46849877/162848251-d9881806-0f7f-4d1c-a422-884c81d994a0.gif)
(right now you have to click on every Toggle)

The same with radio boxes: 
![image](https://user-images.githubusercontent.com/46849877/162848590-e621ca1a-afd2-429a-b25b-146e549f33b4.png)

That would be super useful for interacting in realtime with sequencers.

**Comment by timothyschoen** [comment]
That would be very nice indeed, and for the radioboxes it should be doable. 

For the toggles, I'm not sure yet, I might be able to capture the MouseEnter and MouseExit events and then check if the mousebutton is down? I'll see how it goes!

**Comment by ludnny** [comment]
For the radioboxes, I mean one single click affecting different radioboxes
![33](https://user-images.githubusercontent.com/46849877/162937433-fdc7d435-0b63-48fd-95a6-bb1def049e0c.gif). 
(here is the actual behaviour, it would be nice to have the same with one single click)

In general this behaviour of clicking/dragging would affect all objects. (click on toggle, drag, hover a radiobox, hover a bang...)

I don't know if it's a good practice in general, but I find it super useful for rapid interaction in real-time. 

I tried to find examples in other softwares, and it looks like Ableton Live works like this, one click+drag
![34](https://user-images.githubusercontent.com/46849877/162938351-8d1a967c-dfd5-4e15-a9af-b2f34cacabf4.gif)

**Comment by timothyschoen** [comment]
I understand what you want with the radioboxes now, I think this looks great! And nice that you found a reference of other software that does this. This feature is probably coming soon!
