### ISSUE TITLE
vu not working correctly

### ISSUE THREAD

**Issue by ludnny** [timothyschoen/PlugData#57]
Hi, 

adc~ is not working
The microphone input seems ok in the settings (the vu-meter in the settings is moving)
![image](https://user-images.githubusercontent.com/46849877/162850386-a2d56abd-7762-458e-a726-0b90b0268de0.png)

But when the adc~ is connected to a dac~, no sound...

By the way the vu-meters (vu objects) are not working. 
That would be nice to be able to add them using the + menu as well. 

(I report here everything I see, I guess you are already aware of most of them!)

Tested on 4.0.2 Win64 Standalone.

**Comment by timothyschoen** [comment]
I'm not aware of all of these, so thanks for taking the time to report everything! It's very helpful!

I'll try to get this bug sorted out soon, it's important to have audio in pd!

**Comment by timothyschoen** [comment]
This bug also affects MacOS and presumably Linux.

**Comment by timothyschoen** [comment]
The adc should be fixed!

The VU meter is not finished yet, I'll leave this bug open until it's done. Right now, it shows the input value and draws it nicely but the scaling for the input and output is wrong, it only shows values above 0.

**Comment by timothyschoen** [comment]
VU meter should work now
