### ISSUE TITLE
Feature Request - UI - Multiple triggering ("Trigger selected objects")

### ISSUE THREAD

**Issue by ludnny** [timothyschoen/PlugData#58]
Hi!

It would be nice to be able to trigger multiple objects at the same time. 

In Edit Mode, the user selects multiple objects (could be toggles, radioboxes, bangs, messages...) 
When he presses a keyboard shortcut (Trigger selected objects), that triggers all the selected objects at once.

![image](https://user-images.githubusercontent.com/46849877/163034938-3f49201e-91f0-4390-9f9b-1dc56a756636.png) 
(for radioboxes, that jumps to the next state)

This is something very natural when making music with hardware synths (you can easily trigger multiple buttons at the same time with different fingers), but difficult in software with the mouse.

**Comment by timothyschoen** [comment]
I like this idea as well, but this one will be even trickier to pull off. I'll add this someday probably.

**Comment by timothyschoen** [comment]
Merge this issue into intelligent patching
