### ISSUE TITLE
Bug: messages are printed twice

### ISSUE THREAD

**Issue by ludnny** [timothyschoen/PlugData#59]
After clicking a message once.

Expected:
![image](https://user-images.githubusercontent.com/46849877/163040704-56f33d7b-63c2-45aa-aa7e-cc4d2a745285.png)

Result in 4.0.2 Win34 Standalone:
![image](https://user-images.githubusercontent.com/46849877/163040805-2497349b-2f8b-454c-8257-5f39788539a8.png)

(plus: the message is sent on mouse-up, not on mouse-down as expected)

**Comment by timothyschoen** [comment]
Fixed!

**Comment by ludnny** [comment]
Works in 0.5 :)
