### ISSUE TITLE
OSX issue with standalone

### ISSUE THREAD

**Issue by 60-hz** [timothyschoen/PlugData#6]
I've got a message when I launch the app under Catalina saying that I am using macOS 10.15.4 and the app requires macOS 11.0 or later.

**Comment by timothyschoen** [comment]
Thanks for reporting this, @porres this might be why the plugin didn't load for you! I've set the minimum to El Capitan now, that should be good enough

**Comment by 60-hz** [comment]
@timothyschoen The problem is that the app cannot be launched at all on my OSX ;

![Capture d’écran 2022-01-06 à 20 27 29](https://user-images.githubusercontent.com/5449719/148439901-03823ea1-4313-420d-9753-31f31660d7ca.png)
)

**Comment by timothyschoen** [comment]
This is the downloaded release version right? I will update that with all the new fixes in a few days. Anyways I suspect the reason the app doesn't start for you is the same reason as why the plugins don't load on Catalina.

**Comment by 60-hz** [comment]
>This is the downloaded release version right? 
Yes, it is the release 0.1

**Comment by porres** [comment]
I missed the fact there was a standalone :)

I get the same issue on mojave, an app I can't open. And the warning.

"You can’t use this version of the application “PlugData” with this version of macOS."

"You have macOS %@. The application requires macOS %@ or later."

**Comment by timothyschoen** [comment]
I've uploaded v0.2, this should be fixed

**Comment by 60-hz** [comment]
fixed!
