### ISSUE TITLE
Bug: abstractions don't trigger Loadbang at creation

### ISSUE THREAD

**Issue by ludnny** [timothyschoen/PlugData#62]
Hello!

To reproduce it:

- Create a patch "Loadbang-abs.pd" with Loadbang -- Print
![image](https://user-images.githubusercontent.com/46849877/163427924-2eef0306-ab17-438f-b535-61aa7a7e70d7.png)
- In same folder create patch "Loadbang.pd"
- In Loadbang.pd create an object Loadbang-abs

Expected behaviour (e.g. in Pure Data 0.51.4): Bang is printed in console at object creation

This bug brings multiple problems in Automatonism (state saving)

Tested on 4.0.2 Win64 Standalone

**Comment by timothyschoen** [comment]
Apparently, loadbangs are not triggered on abstractions when you create an object through a message to pd. It's fixed in PlugData, but I assume this might also affect dynamic patching in pure-data.
