### ISSUE TITLE
FeatureRequest: Sizes of objects

### ISSUE THREAD

**Issue by ludnny** [timothyschoen/PlugData#63]
Possibility to change the size (height) of objects. 

![image](https://user-images.githubusercontent.com/46849877/163454309-82778c8c-eed0-4bc3-8c53-c388e74e093a.png)

It would be nice if the sizes in pixels could be exactly the same as in Pure Data. 
At the moment they are almost twice bigger, so a lot of patches from PureData are difficult to read. 

It looks like the HSliders are exactly the same as in PureData, but not the Numbers, Toggles and Bangs.

**Comment by timothyschoen** [comment]
I was planning to look at this as the last big step for fixing #36, so thanks for for making my life easier with this comparison!

**Comment by timothyschoen** [comment]
Toggles and bangs didn't work very well at such a small size because the inlets/outlets are too big. I've made inlets/outlets a little bit transparent when none of them are hovered, similar to Max/MSP. The inlets and outlets will also shrink a bit if you make it really small. That helps a lot already

**Comment by timothyschoen** [comment]
<img width="267" alt="Screenshot 2022-04-16 at 15 59 03" src="https://user-images.githubusercontent.com/44585538/163677756-1aa13006-db18-4481-8c25-ec95a9ee5752.png">
<img width="315" alt="Screenshot 2022-04-16 at 15 59 21" src="https://user-images.githubusercontent.com/44585538/163677758-82193152-5cbe-4098-8039-97d3a934b138.png">

Getting better...

**Comment by timothyschoen** [comment]
Should be fixed in the release I'm uploading right now, feel free to reopen if there's still any problems with this!
