### ISSUE TITLE
PlugData Vst3 not working in Cubase 12 on Mac M1!

### ISSUE THREAD

**Issue by jaffasplaffa** [timothyschoen/PlugData#64]
Hello :) 

I have PlugData working in Logic X Pro. But when I am trying to use PlugData in Cubase 12 it won't verify the PlugData.Vst3 or PlugDataFx.Vst3.

I get this error:
<img width="263" alt="Screenshot 2022-04-15 at 13 39 10" src="https://user-images.githubusercontent.com/14827192/163566785-9fd349f8-3e5b-4598-9ba7-bdfdcb211c91.png">

I did try opening Secuirty and Privacy settings in OSX and allow PlugData manually, but still it doesn't work. Every time I open Cubase I have to go through the manual verification, but even after doing these steps, it won't work:

<img width="672" alt="Screenshot 2022-04-15 at 13 43 39" src="https://user-images.githubusercontent.com/14827192/163567056-def2c6b8-f34a-4c20-89ac-7dae1d154748.png">

I am on latest Cubase 12, latest PlugData and OSX 11.6.5.

Any suggestions to what I can try? 

I am out of ideas, the manual verification, which in most cases work, doesn't work in this case

**Comment by timothyschoen** [comment]
I haven't tested it in Cubase yet, so If there's a trial, I'll test it out.

I thought I signed and notarised everything I uploaded for macOS, but apparently it doesn't work for the vst3 plugins. Thanks for reporting!

If you want to fix it manually, you could build from source Someone made a tutorial for how to do this on Mac: https://www.youtube.com/watch?v=dJK0zbEsFOs

**Comment by jaffasplaffa** [comment]
Thanks for the quick answer :) 

Since Cubase is not using the USB dongle anymore, they do now offer a fully working 30 day trial:
https://www.steinberg.net/cubase/trial/

I have build some stuff before, like PD and lots of stuff for VCV, but I have not setup any dev stuff on this new computer yet.

I am not in a rush, just thought I'd mention it :) 

Happy Easter!

**Comment by timothyschoen** [comment]
Does this still happen?

**Comment by timothyschoen** [comment]
The binaries should definitely by verified now!
