### ISSUE TITLE
Request for implementing the help browser!

### ISSUE THREAD

**Issue by jaffasplaffa** [timothyschoen/PlugData#69]
Hello :) 

In Pure Data if you push command+b(on Mac) you open the help browser. I use the help browser as kind of a patch browser. You simply just add a folder with your PD patches as a "path" and then you can quickly browse around patches. You simply push command+b and you have all the patches right at your finger tips.

I checked the menus and it does not look like the help browser can be accessed or changed from anywhere inside PlugData. 

I'd suggest maybe in the log on the right side of PlugData, maybe that could have a button, next to "restore logs" and "show error", that would let you show the help browser, instead of the log window.

To me the help browser plays a huge role in having a pretty fluent and fast PD experience. Would love to see the help browser ported over to PlugData.

Is that something you would consider?

Thanks in advance, 
Jakob

**Comment by timothyschoen** [comment]
Nice idea, I definitely wanna do this! This is actually also really nice for my own development/testing workflow!

It might take me some time to get to this because there's still a lot that needs to be done, and this is a pretty big feature.

**Comment by timothyschoen** [comment]
![image](https://user-images.githubusercontent.com/44585538/164944566-a887bfa1-31b3-4082-8c23-f5c9016e1e99.png)

Looks like Kiwi has something similar, since it's also made with JUCE it should make it a lot easier.

**Comment by jaffasplaffa** [comment]
Yes, that looks pretty nice, actually :) 

Anything that let's you browse patches faster would be most welcome :)

**Comment by timothyschoen** [comment]
Turns out it wasn't that hard, it works now!


<img width="1054" alt="Screenshot 2022-04-24 at 02 53 08" src="https://user-images.githubusercontent.com/44585538/164951042-c8420e73-4bfb-40eb-9ad4-4fcd0abbdb4b.png">

One small problem was, I couldn't really put the button at the bottom of the console because those buttons disappear when the console isn't selected. So I just added it to the statusbar, I'll also set up a keyboard shortcut for it!

**Comment by timothyschoen** [comment]
I might add some more features and a nicer look to this later, but for now it's done!

**Comment by jaffasplaffa** [comment]
Wauw!

I am sure this is going to make the user experience a lot faster and more fluent :) 

Great job!

**Comment by timothyschoen** [comment]
<img width="301" alt="Screenshot 2022-04-24 at 15 22 55" src="https://user-images.githubusercontent.com/44585538/164978615-5886d8b9-4a6b-4f5a-bf5a-71ec032d289a.png">

Added a search feature and some buttons to:
- Reveal selection in native file explorer
- Choose folder to show
- Reset to default folder

**Comment by jaffasplaffa** [comment]
Looks good :) 

is it possible to add folders/patch, like how it works in PD? Or yeah, maybe we could probably just make an alias/shortcut in the ~/library/PlugData folder to the folder we have our patches in.

**Comment by timothyschoen** [comment]
I want to add a drag/drop feature to it, which will make a shortcut like you suggested. At some point in the future, I hope to also make it work as a media library to add audio files into a patch, but that's something for later.

How do you add folders in pd-vanilla? Maybe I'm stupid but I couldn't figure it out, dragging didn't work for me

**Comment by jaffasplaffa** [comment]
Heh again :) 

If you want to add a folder, you go to dropdown menu Pd>Preferences>Path. 

You can add any folder path right there. It is also used to access externals, you have to add external folders that way too.

**Comment by timothyschoen** [comment]
Ah, that makes sense. For now I'm sticking with the drag/drop + aliases method, but I might let it make aliases for paths automatically later.

**Comment by jaffasplaffa** [comment]
I think making aliases inside the PlugData folder is simpler than having to add them to Path. 

At least for patches it will work, I think :)
