### ISSUE TITLE
Missing dll under windows standalone

### ISSUE THREAD

**Issue by 60-hz** [timothyschoen/PlugData#7]
Under Windows 10 with standalone version, a message say that those dll are missing and are required:
MSVCP140D.dll
VCRUNTIME140D.dll
VCRUNTIME140_1D.dll
ucrtbased.dll

**Comment by timothyschoen** [comment]
Hmm looks like you need Microsoft Visual C++ runtime. You can find it here:

https://aka.ms/vs/17/release/vc_redist.x64.exe

Does that help? I'll have to make an installer eventually so this gets installed automatically. Also thanks for the cross-platform testing! There have been a bunch of fixes already based on feedback, so expect a better release soon. Apparently the VSTs don't always show up on Windows.

**Comment by 60-hz** [comment]
Thanks for this great project ;)
Unfortunately installing the VC runtime did not resolve the issue: same message about missing dll

**Comment by timothyschoen** [comment]
I'll make sure this is sorted out by the time I put the next release up, I think I've found the cause for this problem.

**Comment by timothyschoen** [comment]
I've not been able to reproduce this, but I think is was caused by accidentally uploading a "Debug" build instead of a "Release" build. Can you try the new release to see if it works now?

**Comment by 60-hz** [comment]
Great, I can launch it now, congratulation for the work!

**Comment by timothyschoen** [comment]
Thanks and thanks for testing!

**Comment by 60-hz** [comment]
A small Detail: there is a file called PlugData-Win64.zip inside another file PlugData-Win64.zip
