### ISSUE TITLE
UI bugs and problems in 0.5

### ISSUE THREAD

**Issue by 60-hz** [timothyschoen/PlugData#71]
Tried under MAcOS 10.15.4:

- [x] - hradio, vradio, vslider -> no size limit when resizing using mouse -> can lead to visual issues (only hslider have limit).
- [x] - number box and font is resizable but not floatatom / symbolatom boxes.
- [x] - vradio / hradio -> visual feedbak & output value on mouseup, should be mousedown.
- [x] - list atom :  no interactive float value in box yet.
- [x] - vlider/hslider doesn't follow the dark theme at creation
- [x] - print:  print a list like "println" 
- [x] - adding canvas in light mode make it hardly visible because of same color as background
- [x] - [tgl] is missing "non zero value" property
- [x] - property panel is displayed on mouseup instead of mousedown on a gui
- [x] - center cursor while typing is a bit weird (use to be left centered on pd)
- [x] - adding message with "m" shortcut doesn't activate text typing in message box like "n" is doing for object.
- [x] - Presentation mode : what's the use of "edit mode" in presentation? User can create boxes... but not moving boxes / make connections.

**Comment by timothyschoen** [comment]
Thanks for reporting, I'll fix these soon!

**Comment by timothyschoen** [comment]
The atoms are resizable, but because pd implemented it as a drop-down menu, I also implemented it as a menu in the inspector.

**Comment by 60-hz** [comment]
Sorry, I was not clear on this one, I meant the font is not resizable using mouse on atoms box.
But I can understand now that atoms boxes could be linked to patch's font size in "auto" mode or have a small ranges of sizes in the drop-down menu... also pd gui's are currently under rework so maybe this behavior will change in a next version.

**Comment by timothyschoen** [comment]
Most of these are fixed, the rest is planned for v0.6

**Comment by timothyschoen** [comment]
Should be all fixed now!
