### ISSUE TITLE
Intelligent patching

### ISSUE THREAD

**Issue by ludnny** [timothyschoen/PlugData#72]
Hi, 

This is not something very urgent before a v1.0, but it could hugely improve the patching experience. 

- Ctl+K to connect two selected objects

- Ctl+K to insert an object between two linked objects when the three of them are selected
![35](https://user-images.githubusercontent.com/46849877/165090327-02797eb0-bdb4-45d7-8648-e53c46c38224.gif)

- Edit / Paste Replace (+ keyboard shortcut, this is missing in PureData)

- All the super convenient shortcuts mentionned by IOhannes m zmölnig in these videos:
https://vimeo.com/273707442
https://vimeo.com/279631360
https://vimeo.com/340437816

**Comment by ludnny** [comment]
In the same kind of fast patching ideas, there is this prototype of _keyboard only patching_ by @HenriAugusto :

https://github.com/pure-data/pure-data/pull/869 
![83077201-4e9c1800-a04d-11ea-8824-830d39106eda](https://user-images.githubusercontent.com/46849877/165102264-57ef44d6-322f-45eb-81b9-3137a4af5bad.gif)

**Comment by timothyschoen** [comment]
- [ ] Multiple triggering (trigger selected objects)
- [ ] Click-and-drag activation (toggles and radiobuttons)

**Comment by HenriAugusto** [comment]
> In the same kind of fast patching ideas, there is this prototype of _keyboard only patching_ by @HenriAugusto :
> 
> [pure-data/pure-data#869]

Hi!

I'm glad the prototype catched your eye! I definitely need to get back on this one day. I didn't touch it since the pandemic.

Still, if you don't mind a random crash once in a while you can compile from the last commit. To this day I didn't find anyone who actually tested it!

**Comment by timothyschoen** [comment]
Great design, I'm planning to add some of this to PlugData soon. It's really good for accessibility!

**Comment by JoshuaACNewman** [comment]
Ironically, one of my students who's very interested has cerebral palsy and works much better with a mouse than a keyboard. We might wind up building a macro pad for her that could be a broadly useful creative tool, but chords are particularly difficult, like for switching Edit on and off.

But dragging solutions like above could make things much faster for her.

**Comment by timothyschoen** [comment]
https://user-images.githubusercontent.com/44585538/177019621-f4f77063-eca0-41f8-9f50-9582c447d706.mov

This and more intelligent patching is coming soon!

**Comment by timothyschoen** [comment]
https://user-images.githubusercontent.com/44585538/177020673-7c6de408-77fa-4680-9f27-a71df131d52f.mov

Also works like this with shift down

**Comment by timothyschoen** [comment]
https://user-images.githubusercontent.com/44585538/177045475-3dbf4eef-0728-46ef-b946-10957a0e344f.mov

Dragging over toggles, radioboxes and bangs!

**Comment by ludnny** [comment]
> Dragging over toggles, radioboxes and bangs!

Amazing! Thank you!

**Comment by timothyschoen** [comment]
https://user-images.githubusercontent.com/44585538/177046511-939a95e7-69ee-4705-88c7-107fa4a09a05.mov

Another one with holding shift down.

I was wondering if we should use shift for the drag-toggle behaviour? Might prevent the user from accidentally toggling things, but I'm unsure. So far, shift is used for every intelligent patching option, which makes it pretty easy to memorise and use.

**Comment by ludnny** [comment]
> I was wondering if we should use shift for the drag-toggle behaviour? Might prevent the user from accidentally toggling things, but I'm unsure. So far, shift is used for every intelligent patching option, which makes it pretty easy to memorise and use.

I don't think it's necessary to use Shift to prevent accident toggling. 
I don't remember having problems with Ableton Live (you can test multi-toggling with MaxMidiEffects/Arp)

**Comment by timothyschoen** [comment]
https://user-images.githubusercontent.com/44585538/177056392-bb87fa08-c273-4d93-968f-44e3e3b9e997.mov

If there's only one object selected, holding down shift will trigger this behaviour. If there are multiple objects selected, it will create multiple connections at once instead. I feel like this is pretty intuitive, let me know if you disagree.

This is the last one I'm adding before v1.0, after that I'll open a new ticket so we can discuss more options. I'd like to make sure these options work perfectly first though.
