### ISSUE TITLE
PlugData freezes if you double mouse click a folder in the browser!

### ISSUE THREAD

**Issue by jaffasplaffa** [timothyschoen/PlugData#87]
Hey :) 

Awesome updates for PlugData!

And thanks for the mentioning in the new release ;) 

For the object browser I did notice that if you double click a folder in the browser, PlugData freezes, I get the spinning ball. I tried it a few times and should be replicable just open the browser and double click a folder and it freezes.

In the original version of PD, if you double click a folder in the browser, it shows the original folder in Finder. I think that would nice to replicate, if possible :) 

(I am running PlugData 0.5.1, on OSX 11.6.5 on the basic model M1 Macbook).

**Comment by timothyschoen** [comment]
Oh man what an oversight! I'll add the reveal in file browser behaviour, I like that!

**Comment by timothyschoen** [comment]
Fixed!
