### ISSUE TITLE
Several GUI/Text issues on Windows 10 VST3

### ISSUE THREAD

**Issue by alfonso73** [timothyschoen/PlugData#88]
Hi all,
last update randomly crash several times or freezes Reaper GUI.
Typing object names gives wrong characters (i.e, if i type any letter random characters are written)
I can't type i.e the tilde char as usual on my keyboard (ALT+num pad 126)...a question mark "?" come out instead of tilde "~".
best and thanks @timothyschoen for your great work and effort!

**Comment by timothyschoen** [comment]
Thanks for reporting! That's very strange, and this didn't happen in 0.5? I have honestly no idea how this could happen, and I also can't reproduce it in Reaper :(

**Comment by alfonso73** [comment]
@timothyschoen i'll try to make a video capture of what happens

**Comment by timothyschoen** [comment]
Thanks! You do have the "send all keyboard input to plug-in" option enabled right? And what keyboard layout are you using?

**Comment by alfonso73** [comment]
> Thanks! You do have the "send all keyboard input to plug-in" option enabled right? And what keyboard layout are you using?

oops...i forgot to reactivate "send all keyboard input to plug-in". Now text seems to work fine...but still a lot of instability/freezing/crashing on Win10/Reaper (64x)...i go test on other hosts....

**Comment by timothyschoen** [comment]
I found the cause of the crashes, I'm hoping to upload a new version tonight with all these problems solved!

**Comment by alfonso73** [comment]
@timothyschoen great! thanks

**Comment by timothyschoen** [comment]
Bug should be fixed now, original issue also fixed!
