### ISSUE TITLE
x86 vst3/vsti3 crashes win10

### ISSUE THREAD

**Issue by offthesky** [timothyschoen/PlugData#89]
if i load the vsti or vst fx in reaper(latest) x86 and then load any other plugin after loading plugdata, then reaper crashes immediately. this didn't happen with .5 but seems to be happening with .5.1. not sure if this is related to issue #88 or not.

**Comment by timothyschoen** [comment]
Thanks for reporting! There seem to be some Windows and REAPER related bugs in the last version, I'll get to the bottom of it!

**Comment by offthesky** [comment]
i was just able to try the x64 lv2 in reaper as well as the x64 vst3s in ableton, and all were causes crashes after closing the guis

**Comment by timothyschoen** [comment]
I've noticed! Fixing this is my top priority now!

**Comment by offthesky** [comment]
super lovely plugin/idea btw and i really look forward to using for personal projects as well as a teaching tool in some of my sound design classes :)

**Comment by timothyschoen** [comment]
I'm actually working on some things to improve PlugData as a teaching tool, mostly fast access to parts of documentation like this:

Show object arguments after typing object name:
<img width="542" alt="166109006-48fc8a4c-6320-4219-900e-8433c4c54e4f" src="https://user-images.githubusercontent.com/44585538/167453305-aed75430-cae6-48b2-934b-a183c488f18f.png">

Hover messages that tell you what inlet/outlets do:
![165484758-5232c94a-b6d6-4058-bb1f-122061aaa4ed](https://user-images.githubusercontent.com/44585538/167453353-630925a8-a79f-4da6-b475-0332c7dbc072.gif)

**Comment by offthesky** [comment]
oh wow yeah look fwd to those features - tooltips/hints would be amazing!! also i noticed some of the modules don't have help files associated.  id certainly be happy to create those, if need be, to add to the educational ease of use of this plugin (unless of course, they already exist somewhere).

**Comment by timothyschoen** [comment]
Pretty much everything should have a help file, but maybe it can't find them... Which objects have this problem?

**Comment by timothyschoen** [comment]
It seems like it isn't finding them for cyclone, I'll look into it!

**Comment by timothyschoen** [comment]
Issue is fixed!
