### ISSUE TITLE
x64 & x86 vst - no midi output

### ISSUE THREAD

**Issue by offthesky** [timothyschoen/PlugData#92]
i've got the midiin connected to the midiout (thru) but not seeing any activity on the other side in the midi logger (the midi out indicator in the gui also shows nothing). i see the number boxes showing data moving in from the inputs but nothing seems to be passing to the output.  same goes for ctlout (also seems to be the case w noteout as well).

![plugdata-midioutnoworky](https://user-images.githubusercontent.com/95579081/167521394-39ee45fa-70dc-4c9c-af50-cd88dfb3f43f.png)

what's weird is if i attach a slider to the ctlout's left most in port, and click+drag the slider manually up and down, i see activity coming out of the plugin. but only when im clicking and dragging it manually.

![plugdata-midioutnoworky2](https://user-images.githubusercontent.com/95579081/167521820-3767403b-575c-4232-bd78-2c2510f969f6.png)

couldn't find anything in the settings pertaining to midi out. guess im used to m4l pass stuff through. perhaps im just overlooking something painfully obvious here or is there perhaps a bug?

**Comment by timothyschoen** [comment]
I can reproduce this, it's definitely a bug :(

**Comment by alfonso73** [comment]
confirmed. i can reproduce it to

**Comment by timothyschoen** [comment]
Fixed!
