### ISSUE TITLE
Some more crashes with PlugData VST3 on Windows using ELSE abstractions/objects

### ISSUE THREAD

**Issue by alfonso73** [timothyschoen/PlugData#93]
Hi, .i still have several and frequent crashes in Reaper (64x) with PlugData VST3. I'm often using ELSE stuff and did some test with [bl.vsaw~] that's actually an ELSE oversampling abstraction containing the ELSE object [vsaw~]. Probably there's is something goin' on...i'll test with pure PD objects to see if i have frequent crashes to.

**Comment by timothyschoen** [comment]
I'm curious to see what you'll find! Currently, the Windows version could use the most testing of them all, I'm a bit more comfortable on Mac and Linux so I tend to test more there (which was very obvious in the last release... whoops)

I find that frequent crashes on one platform can sometimes have the same cause as (less frequent) crashes on other platforms, so if you find any patterns in the crashes that'd be very helpful. I'll also start testing on Window more thoroughly for the next versions.

On Mac and Linux there are also occasional crashes, PlugData (and pure-data) can do so many different things that it'll still take some time before it's completely stable. But considering that the project started in November last year, I think that it's manageable to create a mostly stable version in 1-2 months. The good news is that feature-wise it's almost complete for v1.0: All I want to add from now are intelligent patching and opening patches from command line. After that the focus will be completely on stability/fixing issues, documentation, pd compatibility (making sure all objects work properly) and performance.

**Comment by alfonso73** [comment]
@timothyschoen i'll definetly do more test and try to help support your great project. Thanks for your effort! I appreciate it a lot!

**Comment by alfonso73** [comment]
Doing some more test! Overall stability seems good here on my Win10 i7 7700k desktop...definitely worst on my Win11 i9 9900k laptop. Should i post some more findings (something about automation and i suspect UI/DSP thread separation) in separare issue or at the 0.52 discussion thread?

**Comment by timothyschoen** [comment]
Interesting that the bugs come out more on Windows 11, I hope that's a coincidence (it can be) and not a problem with JUCE.

You can create a new issue for thread safety issues, I'm curious about the details!

**Comment by timothyschoen** [comment]
Closing this because there currently isn't enough information to find out what's going on
