### ISSUE TITLE
Crash when edit after a pinch zoom

### ISSUE THREAD

**Issue by 60-hz** [timothyschoen/PlugData#98]
- Create a new object box with "n"
- Change zoom with pinch
- Type any letter =  crash

Tried with MacOS Cattalina 10.15.4 (19E266) and PlugData v0.5.2

**Comment by timothyschoen** [comment]
I can reproduce this, working on it!

**Comment by timothyschoen** [comment]
It appears to be a problem with JUCE, or maybe I'm just stupid. The easiest solution is to just not allow zooming while editing, which is fine imo, who needs that anyway.

**Comment by timothyschoen** [comment]
Fixed it, turns out I'm stupid!
